Repository jk-labs-inc/jokerace, pull requests merged in 2022-09, with the labels that each got.

#69 bugfix: access other chains without connecting
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/useCheckSnapshotProgress.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug, front-end

#79 bugfix: contest rules creation form inputs
  packages/react-app-revamp/components/FormRadioOption/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
Labels: ux, style

#80 bugfix#56: Display "your remaining votes" after a contest instead of "Your used votes"
  packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
Labels: bug

#83 bugfix: rework submit proposals options
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/schema.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
Labels: ux

#87 bugfix: display 'no submission token'
  packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx
Labels: ux

#89 Bugfix: Rules page displays an error when user wallet isn't connected
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx
Labels: bug

#91 docs: add supabase dumps to repo
  packages/supabase/9-14-22_prod_contests.csv
Labels: documentation

#90 feat: add pagination to votes list in proposal page
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.ts
Labels: enhancement, ux, feat, breaking-changes

#95 bugfix: change button styles in wizard form steps
  packages/react-app-revamp/components/Button/styles.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step1/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step4/TextInstructions.tsx
Labels: ux, style

#96 feat: customize tailwindcss/typography
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: ux, style

#99 bugfix: include against votes in prop sort
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug

#98 bugfix: export contest as csv fails after loading 13 proposals
  packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useExportContestDataToCSV/store.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
Labels: bug

#103 feat: add file extension reminder to tiptap/image prompt
  packages/react-app-revamp/components/TipTapEditor/index.tsx
  packages/react-app-revamp/components/TipTapEditorControls/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
Labels: ux
