Repository jk-labs-inc/jokerace, pull requests merged in 2022-08, with the labels that each got.

#32 Bugfix 29/searching same address twice infinite loading
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug

#34 bugfix: inacurate amount of available votes displayed
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/VotingToken/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
Labels: bug, ux

#36 bugfix: fix image/text not appearing when a proposal content has both
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: bug

#37 ux fix: decrease prompt font size & add divider
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement, ux

#40 feat: one RPC call to rule them all (instead of one call per proposal)
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: enhancement, v2

#41 feat: add view allProposalTotalVotes function
  packages/hardhat/contracts/governance/extensions/GovernorCountingSimple.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app/src/contracts/bytecodeAndAbi/Contest.sol/Contest.json
Labels: feat, rpc

#42 feat: add downvoting to smart contracts
  packages/hardhat/contracts/Contest.sol
  packages/hardhat/contracts/governance/Governor.sol
  packages/hardhat/contracts/governance/extensions/GovernorCountingSimple.sol
  packages/hardhat/contracts/governance/extensions/GovernorSettings.sol
Labels: feat, back-end

#45 bugfix: only parse as embedded tweet if the proposal is just a link to a tweet alone
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isUrlTweet.ts
Labels: bug, front-end

#46 feat: allow contest viewing without connecting
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: front-end, feat

#49 feat: delete proposal
  packages/react-app-revamp/components/_pages/DialogModalDeleteProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isProposalDeleted.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/store.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
Labels: enhancement

#51 bugfix: fix switch network button not appearing when user is on the wrong network
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug, ux

#53 bugfix: fix cap proposal submission check
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
Labels: bug, ux, regression

#57 bugfix: render live contests that close sooner first
  packages/react-app-revamp/pages/contests/live/index.tsx
Labels: bug, front-end

#63 feat: handle errors graciously with react-error-boundary
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/StepIndicator/index.tsx
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: ux
