Repository jk-labs-inc/jokerace, pull requests merged in 2023-07, with the labels that each got.

#299 chain: add celo and zeta
  packages/react-app-revamp/config/wagmi/custom-chains/celoMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/celoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zetaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#300 test: add ERC20 rewards tests
  packages/forge/test/RewardsModule.t.sol
Labels: test

#308 chore: unsure of how it got unsynced, but sync up bytecode
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.1.merkleVotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.1.merkleVotes.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#307 test: withdrawals and not enough rankings
  packages/forge/test/RewardsModule.t.sol
Labels: test

#309 typo: remove incorrect .eth suffix
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
Labels: typo

#312 docs: update README
  README.md
  packages/react-app-revamp/README.md
Labels: documentation

#310 feat: live voting updates, finish rewards, update mobile design
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/Reward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useAvatar/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#313 bug: else logic added for non-v3 contests
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug

#316 bug: remove headers requirement from csv upload
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
Labels: bug

#317 patch PR 1 of sprint ending 7/11/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/supabase/9-14-22_prod_contests.csv
Labels: patch

#320 bug: disable decimals for now
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
Labels: bug

#321 patch PR 2 of sprint ending 7/11/23
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
Labels: patch

#325 docs: add note for no decimals
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
Labels: documentation

#326 patch PR 3 for sprint ending 7/11/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
Labels: patch

#329 chore: revert decimal disabling and add docs about dupes
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
Labels: chore

#330 patch PR 4 of sprint ending 7/11/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
Labels: patch

#323 bug: connected address doesn't show in top voters
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
Labels: bug

#324 chore: rename top voters to voters to avoid confusion
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
Labels: chore

#331 bug: contest title is not showing in the head of URL
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: bug

#332 bug: add csv validations for 0 addresses, duplicates or 18 decimals, …
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
Labels: bug

#334 chore: remove Contest from title
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: chore

#335 patch PR 5 of sprint ending 7/11/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: patch

#337 bug: fix error while casting votes
  packages/react-app-revamp/hooks/useContestEvents/index.ts
Labels: bug

#338 bug: add supabase catch until error handling comes in
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bug

#339 feat: add network name to participants
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: feat

#340 patch PR 6 of week ending 7/11/23
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: patch

#341 chore: don't sort proposal voters
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
Labels: chore

#343 chore: remove mainnet as an option
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#344 patch PR 7 of week ending 7/11/23
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#346 chain: add public goods network testnet
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#348 chain: add loot chain
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#349 patch PR 9 of week ending 7/11/23
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#345 chore: add supabase schemas to repo
  packages/react-app-revamp/supabase_schemas/contest_participants_v3
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: chore

#350 bug: add network name when fetching contest from db in useContest hook
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug

#351 chain: add near aurora
  packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#352 patch PR 10 of week ending 7/11/23
  packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/nearAuroraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/supabase_schemas/contest_participants_v3
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: patch

#342 feat: user state interaction & cosmetics update
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Loading/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionDate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotesDate/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/public/toast/sadboi.png
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/types/error.ts
Labels: feat

#354 bug: return null if user is on tab rewards and there isn't rewards module
  packages/react-app-revamp/components/Rewards/index.tsx
Labels: bug

#355 patch PR 12 of week ending 7/11/23
  packages/react-app-revamp/components/Rewards/index.tsx
Labels: patch

#365 bug: look at chain name in url for share links
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug

#368 chore: delete deprecated contract bytecode
  packages/react-app-revamp/contracts/bytecodeAndAbi/GenericVotesTimestampToken.sol/GenericVotesTimestampToken.json
Labels: chore

#369 feat: cosmetics + overall updates pt2
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/Slider/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Tab/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/ProposalStatistics/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#375 bug: revert toast bg color for default ones
  packages/react-app-revamp/styles/globals.css
Labels: bug

#374 bug: fix rewards info in contests card
  packages/react-app-revamp/lib/contests/index.ts
Labels: bug

#371 chain: add gnosis chain
  packages/react-app-revamp/config/wagmi/custom-chains/gnosisMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gnosisTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#376 patch PR 1 of week ending 7/18/23
  packages/react-app-revamp/config/wagmi/custom-chains/gnosisMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gnosisTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: patch

#377 chore: update version to 3.2
  packages/forge/src/governance/Governor.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.2.totalVotesCast.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.2.totalVotesCast.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#378 patch PR 2 of week ending 7/18/23
  packages/forge/src/governance/Governor.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.2.totalVotesCast.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.2.totalVotesCast.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: patch

#382 bug: fix rich text editor on firefox
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/editor.ts
  packages/react-app-revamp/tailwind.config.js
Labels: bug

#383 patch PR 3 of week ending 7/18/23
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/editor.ts
  packages/react-app-revamp/tailwind.config.js
Labels: patch

#387 docs: update schema filetype to sql
  packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
Labels: documentation

#388 chain: add public goods network mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#386 patch PR 4 of week ending 7/18/23
  packages/react-app-revamp/.eslintrc.json
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/schema.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/TimelineV3/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
  packages/react-app-revamp/types/error.ts
Labels: patch

#390 docs: update TOS
  TOS.md
Labels: documentation

#392 feat: cosmetics and overall updates pt4
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/ProposalStatistics/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
Labels: feat

#393 bug: add optimistic approach for voting popup cast votes and available amount
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
Labels: bug

#394 patch PR 5 of week ending 7/18/23
  TOS.md
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/ProposalStatistics/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
Labels: patch

#396 feat: rewards module ui/ux & code polish
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#395 bug: fix totalVotesCast check
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug

#397 patch PR 6 of week ending 7/18/23
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: patch

#398 bug: timeout fails if too many milliseconds, so just cap max timeout
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug

#399 patch PR 7 of week ending 7/17/23
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#402 chore: refactor chains to be explicitly defined
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#403 feat: cosmetics updates
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Tabs/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: feat

#405 chore: remove extra provider env vars
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#406 chore: up to 100k allowlists
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
Labels: chore

#408 bug: add https to pgn mainnet rpc
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkMainnet.ts
Labels: bug

#409 merge sprint ending 7/18/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Tabs/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: sprint end

#413 chore: remove unused env vars
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/urql/index.ts
  packages/react-app-revamp/config/web3storage/index.ts
Labels: chore

#416 patch PR 1 of week ending 7/25/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
  packages/react-app-revamp/config/urql/index.ts
  packages/react-app-revamp/config/web3storage/index.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#417 chain: add mantle
  packages/react-app-revamp/config/wagmi/custom-chains/mantleMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#418 patch PR 2 of week ending 7/25/23
  packages/react-app-revamp/config/wagmi/custom-chains/mantleMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#419 feat: cosmetics update
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionDate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: feat

#423 bug: fix broken images
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
Labels: bug

#424 patch PR 3 of week ending 7/25/23
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionDate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: patch

#404 feat: rewards module final polish
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/public/rewards/distributed-ellipse.svg
  packages/react-app-revamp/public/rewards/no-funds-distributed-ellipse.svg
  packages/react-app-revamp/styles/globals.css
Labels: feat

#427 patch PR 4 of week ending 7/25/23
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/public/rewards/distributed-ellipse.svg
  packages/react-app-revamp/public/rewards/no-funds-distributed-ellipse.svg
  packages/react-app-revamp/styles/globals.css
Labels: patch

#429 bug: fix rank in proposals and do not floor vote number in formatNumber
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
Labels: bug

#430 patch PR 5 of week ending 7/25/23
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
Labels: patch

#431 bug: remove alchemy rpc hook, just use custom configs
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: bug

#432 patch PR 6 of week ending 7/25/23
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonMumbai.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#433 chore: update OP RPC to ankr so not being rate-limited, correct Arb testnet
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
Labels: chore

#434 feat: rewards module withdraws
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/PreviouslyDistributedReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: feat

#435 patch PR 7 of week ending 7/25/23
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/NativeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/PreviouslyDistributedReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: patch

#436 feat: add 6 total contests to be featured
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/publicgoodsnetwork.svg
Labels: feat

#438 chore: remove logging
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
Labels: chore

#437 merge sprint ending 7/26/23
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/publicgoodsnetwork.svg
Labels: sprint end

#439 enhancement: don't check submitters if everyone can submit
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
Labels: enhancement

#444 chain: add base mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/baseMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#445 patch PR 1 of week ending 8/1/23
  packages/react-app-revamp/config/wagmi/custom-chains/baseMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
Labels: patch
