Repository jk-labs-inc/jokerace, pull requests merged in 2023-09, with the labels that each got.

#584 feat: add participants and rewards internal analytics components
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
Labels: feat

#586 feat: add message if proposals length reach max proposal count for contest
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
Labels: feat

#587 patch PR 4 of week ending 9/5/23
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
Labels: patch

#588 Revert "enhancement: add meta tags to contest page"
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: bug

#589 patch PR 5 of week ending 9/5/23
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: patch

#592 bugfix: revert #586
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
Labels: bug

#593 bug: check subMerkleRoot instead of deprecated subMerkleTree
  packages/react-app-revamp/lib/contests/index.ts
Labels: bug

#594 patch PR 1 of week ending 9/12/23
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: patch

#595 bug: correctly check submission root
  packages/react-app-revamp/lib/contests/index.ts
Labels: bug

#596 patch PR 2 of week ending 9/12/23
  packages/react-app-revamp/lib/contests/index.ts
Labels: patch

#601 chore: move arb to public rpc endpoint
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
Labels: chore

#602 patch PR 3 of week ending 9/12/23
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
Labels: patch

#609 docs: update used votes wording
  packages/react-app-revamp/components/Voting/index.tsx
Labels: documentation

#617 wording: update text on site
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
Labels: wording

#624 chore: update versions to 3.6
  packages/forge/src/governance/Governor.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.6.bringBackDeletedIds.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.6.bringBackDeletedIds.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#627 chore: switch over to fully free RPC endpoints
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
Labels: chore

#623 feat: delete proposal functionality
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isProposalDeleted.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/store.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: feat

#634 enhancement: hard limit max submissions to 10k
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: enhancement

#636 patch PR 1 of week ending 9/19/23
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: patch

#637 wording: use plural for submissions if applicable
  packages/react-app-revamp/components/Parameters/index.tsx
Labels: wording

#639 chore: update base rpc to publicnode
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
Labels: chore

#640 patch PR 2 of week ending 9/19/23
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
Labels: patch

#641 feat: redirect to submission after user submit
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: feat

#643 bug: fix mantle image typo
  packages/react-app-revamp/config/wagmi/index.ts
Labels: bug

#642 chore: update analytics table to event based
  packages/react-app-revamp/helpers/timestamp.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
Labels: chore

#644 patch PR 3 of week ending 9/19/23
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/timestamp.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
Labels: patch

#646 hotfix: switch public node back to alchemy
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
Labels: bug

#648 patch PR 4 of week ending 9/19/23
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/lib/contests/index.ts
Labels: patch

#654 test: update test documentation and add basic release w deletions tests
  packages/forge/test/Contest.t.sol
  packages/forge/test/RewardsModule.t.sol
Labels: test

#660 chore: add hydration error handling and better system for desktop and mobile versions
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/components/TokenRow/DesktopLayout/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/components/TokenRow/MobileLayout/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/components/TokenRow/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/helpers/getTokenImage.ts
  packages/react-app-revamp/helpers/isTokenShorthand.ts
  packages/react-app-revamp/helpers/mediaQuery.ts
  packages/react-app-revamp/hooks/useCreateFlowAction/store.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#663 bug: revert "feat: make sortedProposals indexable (#653)"
  packages/forge/src/governance/Governor.sol
  packages/forge/src/governance/extensions/GovernorSorting.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/forge/test/Contest.t.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.11.addIndexedSortedProps.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.11.addIndexedSortedProps.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bug

#665 patch PR 7 of week ending 9/19/23
  packages/forge/src/governance/Governor.sol
  packages/forge/src/governance/extensions/GovernorSorting.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/forge/test/Contest.t.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.11.addIndexedSortedProps.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.11.addIndexedSortedProps.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: patch

#667 chore: update submission limit to 1k
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#669 patch PR 8 of week ending 9/19/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: patch

#672 enhancement: index contests_v3 + update schema
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: enhancement

#673 patch PR 9 of week ending 9/19/23
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: patch

#675 enhancement: add participants table index
  packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
Labels: enhancement

#681 bug: fix proposal structure for v2 contests
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: bug

#683 wording: add pluralization to params tab
  packages/react-app-revamp/components/Parameters/index.tsx
Labels: wording

#685 chore: switch out sepolia provider
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: chore

#682 bug: add timeout for unresponsive RPCs
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/timeout.ts
Labels: bug

#686 wording: add text to voting allowlist page
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
Labels: wording

#689 enhancement: dynamically set the count of remaining proposals for skeleton count
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
Labels: enhancement

#690 merge sprint ending 9/19/23
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/timeout.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/supabase_schemas/contest_participants_v3.sql
Labels: sprint end

#692 bug: fix circular dependency warning
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/helpers/csvConstants.ts
  packages/react-app-revamp/helpers/csvTypes.ts
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: bug

#694 bug: icon sizes aren't equal in share dropdown
  packages/react-app-revamp/components/Share/index.tsx
Labels: bug

#701 wording: change wording of rewards module address description
  packages/react-app-revamp/components/Rewards/index.tsx
Labels: wording

#700 chain: add ending slashes to block explorers
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/celo.ts
  packages/react-app-revamp/config/wagmi/custom-chains/celoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
  packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantle.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zetaTestnet.ts
Labels: chain

#704 bug: fix wrong picked proposal when on submission page
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: bug

#702 chore: bring back version param, tests, and fetchSingleProposal from #663
  packages/forge/test/Contest.t.sol
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: chore

#706 chain: add kroma
  packages/react-app-revamp/config/wagmi/custom-chains/kroma.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/kroma.svg
Labels: chain

#693 chore: add better error handling across the app
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/UI/TrackerDeployTransaction/index.tsx
  packages/react-app-revamp/components/UI/TrackerDeployTransaction/styles.module.css
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useCastVotes/store.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContractFactory/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/store.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/store.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useFundRewards/store.tsx
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.tsx
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/store.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/store.tsx
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/types/error.ts
  packages/react-app-revamp/utils/error.ts
Labels: chore

#716 enhancement: add remaining count for list of voters on load more
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.tsx
Labels: enhancement

#715 chore: update max proposal to 100 in order to create rewards module, keep hard limit at 1000
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: chore

#718 patch PR 4 of week ending 9/26/23
  packages/react-app-revamp/helpers/timeout.ts
Labels: patch

#719 docs: add audit link to README
  README.md
  packages/react-app-revamp/README.md
Labels: documentation

#721 docs: rm unaudited note
  packages/react-app-revamp/components/Rewards/index.tsx
Labels: documentation

#720 patch PR 5 of week ending 9/25/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/Rewards/index.tsx
Labels: patch

#723 chore: add error message if RPC call fails
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: chore

#722 feat: add submissions and voting activity to profile
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/helpers/getAddressProps.ts
  packages/react-app-revamp/helpers/routing.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutCreator/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/user/types/index.ts
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: feat

#724 merge sprint ending 9/26/23
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/helpers/getAddressProps.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/routing.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutCreator/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/user/types/index.ts
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: sprint end

#726 chore: update wording in submissions and voting activity on user profile
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
Labels: wording

#725 enhancement: add description when user navigates to deleted proposals
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: enhancement

#727 patch PR 1 of week ending 10/3/23
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#728 chore: refine timestamp handling and error fallbacks
  packages/react-app-revamp/helpers/timestamp.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: chore

#729 patch PR 2 of week ending 10/3/23
  packages/react-app-revamp/helpers/timestamp.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: patch

#735 chore: reorder fe versions
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
Labels: chore
