Repository jk-labs-inc/jokerace, pull requests merged in 2023-04, with the labels that each got.

#239 bug: use chain list defined in config/wagmi instead of network hook
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: bug

#236 bug: contest status floating on proposals page
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug, ux

#235 bug: remove bullet points from pagination on mobile
  packages/react-app-revamp/styles/globals.css
Labels: bug, ux

#248 bugfix: correctly version rewards notes update
  packages/hardhat/contracts/governance/Governor.sol
  packages/hardhat/contracts/modules/RewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.10.betterRewardsNotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.2.5.betterRewardsNotes.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: bug

#249 chore: remove postdeploy
  packages/hardhat/package.json
Labels: chore

#250 bugfix: remove extra chains causing problems
  packages/hardhat/hardhat.config.js
Labels: bug

#255 bugfix: fix supabase error if no env vars
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
  packages/react-app-revamp/config/supabase/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestsIndex/index.ts
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
Labels: bug
