Repository jk-labs-inc/jokerace, pull requests merged in 2023-10, with the labels that each got.

#736 chore: update next and turbo libs
  package.json
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#765 chore: update schemas
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: chore

#772 patch PR 1 of week ending 10/10/23
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/Countdown/index.tsx
Labels: patch

#779 bug: fix proposal voters missing in modal and small refactor on component
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
Labels: bugfix

#780 bug: allow user to see if they are eligible to submit if wallet is not connected
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
Labels: bugfix

#781 bug: add ellipsis on reward token symbol on contest page
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bugfix

#782 chore: add helper function to get chain and address extraction in the app
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/components/TokenRow/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/helpers/extractPath.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: chore

#783 patch PR 2 of week ending 10/10/23
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/components/TokenRow/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/helpers/extractPath.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#784 feat: add okx wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: feat

#786 feat: add taho wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: feat

#785 patch PR 3 of week ending 10/10/23
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#789 chain: make explicit mainnet config
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#790 patch PR 4 of week ending 10/10/23
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#792 enhancement: try passing meta tags with static props
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/index.tsx
  yarn.lock
Labels: enhancement

#793 patch PR 5 of week ending 10/10/23
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/index.tsx
  yarn.lock
Labels: patch

#803 bug: add ethereum logo to wagmi config
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/proteus.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zora.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: bugfix

#806 chore: add bitget wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#809 patch PR 2 of week ending 10/17/23
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/helpers/pwa.ts
Labels: patch

#812 feat: add ability to hide contests
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/creator/index.ts
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/public/user/private.svg
  packages/react-app-revamp/public/user/public.svg
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: feat

#813 chore: remove pull to refresh functionality
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: chore

#815 bugfix: add mainnet ENS resolver config
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
Labels: bugfix

#814 feat: track withdrawals and deletes in analytics table
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
Labels: feat

#818 chain: add scroll mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#819 bugfix: remove duplicated border on list of contests on mobile
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
Labels: bugfix

#820 patch PR 1 of week ending 10/24/23
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#821 bugfix: update twitter regex to match whole html for tweet in proposal content
  packages/react-app-revamp/components/_pages/Contest/components/Proposal/index.tsx
  packages/react-app-revamp/helpers/isUrlTweet.ts
Labels: bugfix

#824 chore: don't filter deleted submissions from user profile results
  packages/react-app-revamp/lib/user/index.tsx
Labels: chore

#825 patch PR 3 of week ending 10/24/23
  packages/react-app-revamp/lib/user/index.tsx
Labels: patch

#829 chore: remove duplicate markdown libs
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#827 enhancement: swipes
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/public/contest/next-entry-mobile.svg
  packages/react-app-revamp/public/contest/next-entry.svg
  packages/react-app-revamp/public/contest/previous-entry-mobile.svg
  packages/react-app-revamp/public/contest/previous-entry.svg
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#828 chore: add ssr for markdown lib
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  yarn.lock
Labels: chore

#833 bugfix: prevent 404 on older contests if no metatags
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: bug

#834 patch PR 4 of week ending 10/24/23
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/public/contest/next-entry-mobile.svg
  packages/react-app-revamp/public/contest/next-entry.svg
  packages/react-app-revamp/public/contest/previous-entry-mobile.svg
  packages/react-app-revamp/public/contest/previous-entry.svg
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch

#844 bugfix: fix add votes functionality on submission page
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
Labels: bugfix

#835 feat: NFT permissioning
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Tab/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useNftTokenDetails/index.ts
  packages/react-app-revamp/hooks/useWebWorker/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/workers/generateRootAndRecipients.ts
  packages/react-app-revamp/workers/indexContestParticipants.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: feat

#846 merge sprint ending 10/24/23
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Tab/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useNftTokenDetails/index.ts
  packages/react-app-revamp/hooks/useWebWorker/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/workers/generateRootAndRecipients.ts
  packages/react-app-revamp/workers/indexContestParticipants.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: sprint end

#847 wording: add message when user is out of votes on proposal card
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: wording

#850 bugfix: separate sorting logic and remove stale times on list of contests
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/hooks/useSortedData/index.ts
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
Labels: bugfix

#848 enhancement: implement flow & style changes to PWA popup
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/SupportedBrowser/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#852 patch PR 1 of week ending 10/31/23
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/SupportedBrowser/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSortedData/index.ts
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/tailwind.config.js
Labels: patch

#859 bugfix: voters same requirements
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: bugfix

#858 chore: add dist func to propose without proof
  packages/forge/src/governance/Governor.sol
  packages/forge/src/governance/IGovernor.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.1.addEntryCharge.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.1.addEntryCharge.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#860 patch PR 2 of week ending 10/31/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: patch

#865 bugfix: refactor qualification message for submitting a proposal
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
Labels: bugfix

#866 bugfix: hide submission navigation containers if there is only one submission in contest
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: bugfix

#862 feat: entry charge frontend
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/shortenEthereumAddress.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useEntryChargeDetails/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/public/contest/wallet-entry-insufficient.svg
  packages/react-app-revamp/public/contest/wallet-entry.svg
  packages/react-app-revamp/public/explainer/small-ellipse-gray.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/chain_params.sql
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: feat

#870 bugfix: handle single or multiple networks messages in entry charge flow
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
Labels: bugfix

#874 chore: update q currency name
  packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts
Labels: chore

#877 bugfix: fix and improve twitter logic
  packages/react-app-revamp/components/_pages/Contest/components/Proposal/index.tsx
  packages/react-app-revamp/helpers/isUrlTweet.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#879 patch PR 4 of week ending 10/31/23
  packages/react-app-revamp/components/_pages/Contest/components/Proposal/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts
  packages/react-app-revamp/helpers/isUrlTweet.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: patch

#878 enhancement: implement logic & design for new contest prompt
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: enhancement

#881 merge sprint ending 10/31/23
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: sprint end

#884 patch PR 1 of week ending 11/7/23
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: patch

#887 chore: use hash proposal fn for proposal id
  packages/react-app-revamp/helpers/getProposalId.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: chore

#888 patch PR 2 of week ending 10/31/23
  packages/react-app-revamp/helpers/getProposalId.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: patch
