Repository jk-labs-inc/jokerace, pull requests merged in 2023-03, with the labels that each got.

#194 refactor: remove export data
  packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
  packages/react-app-revamp/config/react-csv/export-contest.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/export-data/index.tsx
Labels: refactor

#198 enhancement: add caching to create flow
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
  packages/react-app-revamp/helpers/localStorage.ts
  packages/react-app-revamp/helpers/object.ts
Labels: enhancement, ux

#197 bug: fund rewards with matic or other native token
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/schema.ts
Labels: bug, ux, rewards

#199 enhancement: add react-toastify for better toast support
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/ERC20Reward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/NativeCurrencyReward.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
  packages/react-app-revamp/config/react-hot-toast/index.ts
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.ts
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/package-lock.json
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
Labels: enhancement, ux

#207 merge sprint ending 3/21/23
  .github/ISSUE_TEMPLATE/bug_report.md
  package.json
  packages/react-app-revamp/components/UI/Button/styles.ts
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/TipTapEditor/index.tsx
  packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
  packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/schema.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/ERC20Reward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/NativeCurrencyReward.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
  packages/react-app-revamp/config/react-csv/export-contest.ts
  packages/react-app-revamp/config/react-hot-toast/index.ts
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/helpers/localStorage.ts
  packages/react-app-revamp/helpers/object.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/package-lock.json
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/export-data/index.tsx
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: sprint end

#211 chore: update yarn lockfile
  yarn.lock
Labels: chore

#214 bug: fix bug with contest indexing
  packages/react-app-revamp/hooks/useContestsIndex/index.ts
Labels: bug

#213 enhancement: add fadeInOut animation and shadows to toasts
  packages/react-app-revamp/config/react-toastify/animations/FadeInOut.tsx/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#217 bug: remove bullet points from pagination in contests
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: bug, ux

#225 bug: remove modal for minting token if user reject tx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts
Labels: bug

#223 feat: add polygon zkmainnet
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#220 bug: remove duplication of code in useContest hook
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug

#216 feat: search contests by title
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/schema.ts
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/helpers/database.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/types/search.ts
Labels: ux, feat

#227 chore: remove zksync
  packages/react-app-revamp/config/wagmi/custom-chains/zkEraMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#228 merge sprint ending 3/28/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/schema.ts
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/useDeployToken.ts
  packages/react-app-revamp/config/react-toastify/animations/FadeInOut.tsx/index.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zkEraMainnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/database.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/public/forward.png
  packages/react-app-revamp/public/socials/lens.svg
  packages/react-app-revamp/public/socials/twitter.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/types/search.ts
Labels: sprint end

#230 chore: update chain request template w forking
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: chore

#231 patch PR 1 of sprint ending 4/4/23
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#232 feat: add avalanche c-chain
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#233 patch PR 2 of sprint ending 4/4/23
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch
