Repository jk-labs-inc/jokerace, pull requests merged in 2023-05, with the labels that each got.

#256 chore: upgrade to nextjs 13, enhance build time & site speed, remove outdated libs
  packages/react-app-revamp/.eslintrc.json
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step4/TextInstructions.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package-lock.json
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/404.tsx
  yarn.lock
Labels: refactor, chore

#237 feat: landing page
  packages/react-app-revamp/components/Clock/index.tsx
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/Header/index.tsx
  packages/react-app-revamp/components/Search/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/UI/Button/styles.ts
  packages/react-app-revamp/components/UI/Icons/Checkmark/index.tsx
  packages/react-app-revamp/components/UI/Icons/Cross/index.tsx
  packages/react-app-revamp/components/UI/Menu/Link/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/config/rainbowkit/index.ts
  packages/react-app-revamp/config/react-toastify/animations/FadeInOut.tsx/index.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/declarations.d.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useCountdown/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUserBalance/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Timeline/Steps/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/fetchUserBalance.ts
  packages/react-app-revamp/package-lock.json
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/Sabo-Filled.otf
  packages/react-app-revamp/public/base.svg
  packages/react-app-revamp/public/explainer/Arrow1.svg
  packages/react-app-revamp/public/explainer/Arrow2.svg
  packages/react-app-revamp/public/explainer/Arrow3.svg
  packages/react-app-revamp/public/explainer/Arrow4.svg
  packages/react-app-revamp/public/explainer/Arrow5.svg
  packages/react-app-revamp/public/explainer/Ellipse1.svg
  packages/react-app-revamp/public/explainer/Ellipse2.svg
  packages/react-app-revamp/public/explainer/Ellipse3.svg
  packages/react-app-revamp/public/explainer/Ellipse4.svg
  packages/react-app-revamp/public/explainer/Ellipse5.svg
  packages/react-app-revamp/public/explainer/bg-1.svg
  packages/react-app-revamp/public/explainer/bg-2.svg
  packages/react-app-revamp/public/explainer/bg-3.svg
  packages/react-app-revamp/public/explainer/small-ellipse.svg
  packages/react-app-revamp/public/scroll.png
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: feat

#263 refactor: replace all jokedao references
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/config/rainbowkit/index.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/proposal/[proposal].tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
Labels: refactor

#266 feat: add csv to merkle trees
  packages/react-app-revamp/helpers/parseCsv.ts
  packages/react-app-revamp/lib/merkletree/generate.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/index.tsx
  yarn.lock
Labels: feat

#271 merge sprint ending 5/9/23
  README.md
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/submissionCaching.ts
Labels: sprint end

#269 refactor: implement minor visual improvements on landing for both mobile & desktop
  packages/react-app-revamp/components/Clock/index.tsx
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/index.tsx
Labels: ux, refactor

#273 feat: implement SEO enhancements with image, text, and footer links
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/public/card.png
  packages/react-app-revamp/public/jokerace.png
Labels: feat

#275 refactor: update jokerace img
  packages/react-app-revamp/public/jokerace.png
Labels: refactor

#274 merge sprint ending 5/23/23
  packages/react-app-revamp/components/Clock/index.tsx
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/card.png
  packages/react-app-revamp/public/jokerace.png
Labels: sprint end

#276 bug: add try/catch for fetching ENS name
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
Labels: bug

#277 patch PR 1 of sprint ending 5/30/23
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
Labels: patch

#280 refactor: remove fade in animations from landing
  packages/react-app-revamp/pages/index.tsx
Labels: refactor

#281 merge sprint ending 5/30/23
  packages/react-app-revamp/pages/index.tsx
Labels: sprint end
