Repository jk-labs-inc/jokerace, pull requests merged in 2023-02, with the labels that each got.

#147 bugfix: dont display rewards tab when no rewards module found
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bug, ux

#157 docs: add rewards module notes
  packages/hardhat/contracts/modules/RewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: documentation

#113 feat: store and retrieve contest data in csv file
  README.md
  packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
  packages/react-app-revamp/config/react-csv/export-contest.ts
  packages/react-app-revamp/config/web3storage/index.ts
  packages/react-app-revamp/helpers/objectToCsv.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/store.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/contest/[chain]/[address]/export-data/index.tsx
  yarn.lock
Labels: enhancement, feat, breaking-changes

#139 bugfix: Remove event listener on tab isn't focused
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/Reward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/hooks/useContest/store.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug, enhancement

#161 merge sprint ending 2/7/23
  README.md
  packages/react-app-revamp/components/DialogModal/index.tsx
  packages/react-app-revamp/components/_pages/ButtonDownloadContestDataAsCSV/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/schema.ts
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/Reward.tsx
  packages/react-app-revamp/components/_pages/RewardsWinner/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/schema.ts
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/useDeployContest.ts
  packages/react-app-revamp/config/react-csv/export-contest.ts
  packages/react-app-revamp/config/web3storage/index.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/objectToCsv.ts
  packages/react-app-revamp/helpers/ordinalize.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/store.ts
  packages/react-app-revamp/hooks/useExportContestDataToCSV/useExportContestDataToCSV.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useRewardsModule/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/contest/[chain]/[address]/export-data/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
  yarn.lock
Labels: sprint end

#162 chore: add disclaimer on rewards
  packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
Labels: enhancement

#171 chore: add ofac address screening
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step2/index.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/DialogModalMintProposalToken.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/Step3/Form.tsx
  packages/react-app-revamp/components/_pages/WizardFormCreateContest/index.tsx
  packages/react-app-revamp/config/ofac-addresses/ofac-addresses.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Sidebar/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rewards/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/rules/index.tsx
Labels: ux

#184 docs: add chain integration template
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: chain
