Repository jk-labs-inc/jokerace, pull requests merged in 2023-11, with the labels that each got.

#891 enhancement: implement design changes for entry charge in submission popup
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#892 enhancement: implement various design changes in app
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#893 chore: remove entry charge fields if chain is not supported
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useEntryChargeDetails/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
Labels: chore

#894 patch PR 3 of week ending 11/7/23
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useEntryChargeDetails/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: patch

#895 chore: adjust entry charge values to the right
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
Labels: bugfix

#896 patch PR 4 of week ending 11/7/23
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
Labels: patch

#898 patch PR 5 of week ending 11/7/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
Labels: patch

#900 bugfix: check lowercase chain names for entry charge
  packages/react-app-revamp/lib/monetization/index.ts
Labels: bugfix

#901 patch PR 6 of week ending 11/7/23
  packages/react-app-revamp/lib/monetization/index.ts
Labels: patch

#904 bugfix: wrap toast container with portal from headless ui
  packages/react-app-revamp/pages/_app.tsx
Labels: bugfix

#905 patch PR 7 of week ending 11/7/23
  packages/react-app-revamp/pages/_app.tsx
Labels: patch

#911 chore: add gh action to auto-merge main PRs into staging
  .github/workflows/auto_rebase_main_PRs.yml
Labels: chore

#912 patch PR 8 of week ending 11/7/23
  .github/workflows/auto_rebase_main_PRs.yml
Labels: patch

#915 chore: add rabby wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#916 patch PR 9 of week ending 11/7/23
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#917 chain: add artheraTestnet
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#922 docs: renovate the bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#931 chore: fix bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#927 bugfix: only show parenthesis in params if permissioning requirements
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
Labels: bugfix

#926 chore: set reward actions to null if it isn't targeted action
  packages/react-app-revamp/lib/analytics/rewards/index.ts
Labels: chore

#925 enhancement: misc design updates
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#924 feat: add google analytics to frontend
  packages/react-app-revamp/lib/gtag/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/_document.tsx
  yarn.lock
Labels: feat

#923 enhancement: rehaul list proposal votes
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#934 chore: add burger menu to mobile
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/pages/index.tsx
Labels: chore

#935 chore: remove initial focus on burger menu
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
Labels: chore

#933 merge sprint ending 11/7/23
  .github/ISSUE_TEMPLATE/bug_report.md
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/store.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/lib/gtag/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/_document.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: sprint end

#939 bugfix: remove negative margin on editor controls
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
Labels: bugfix

#940 chore: remove auto close on error toast
  packages/react-app-revamp/components/UI/Toast/index.tsx
Labels: chore

#938 chore: add tg handle to bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#941 chore: allow up to 5 decimals in entry charge
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
Labels: chore

#943 chore: update amount sent schema to numeric
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: chore

#942 patch PR 1 of week ending 11/14/23
  .github/ISSUE_TEMPLATE/bug_report.md
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: patch

#948 bugfix: user page incorrect qualification
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/user/[address]/index.tsx
Labels: bugfix

#951 enhancement: bug reporting
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/helpers/githubIssue.ts
Labels: enhancement

#952 enhancement: revamp text when sharing contest on social media
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#954 enhancement: add bug report link in broken url or rpc page
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: enhancement

#955 patch PR 2 of week ending 11/14/23
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/helpers/githubIssue.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/user/[address]/index.tsx
  yarn.lock
Labels: patch

#956 chore: update toast error style
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/utils/error.ts
Labels: chore

#960 enhancement: email subscription ui/ux updates
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/store.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#961 chain: add unique, quartz, and vitruveo
  packages/react-app-revamp/config/wagmi/custom-chains/quartz.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unique.ts
  packages/react-app-revamp/config/wagmi/custom-chains/vitruveo.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/quartz.svg
  packages/react-app-revamp/public/unique.svg
  packages/react-app-revamp/public/vitruveo.svg
Labels: chain

#962 patch PR 3 of week ending 11/14/23
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/quartz.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unique.ts
  packages/react-app-revamp/config/wagmi/custom-chains/vitruveo.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/store.tsx
  packages/react-app-revamp/public/quartz.svg
  packages/react-app-revamp/public/unique.svg
  packages/react-app-revamp/public/vitruveo.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/utils/error.ts
Labels: patch

#963 bugfix: add submissionsCount prop when user submit proposal
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#968 bugfix: prepare contract write in submit proposal
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#970 chore: add more gas error codes
  packages/react-app-revamp/utils/error.ts
Labels: chore

#966 enhancement: contest descriptions
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: enhancement

#972 enhancement: remove share icons in submission on mobile
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#977 merge sprint ending 11/14/24
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/utils/error.ts
Labels: sprint end

#982 chain: add manta
  packages/react-app-revamp/config/wagmi/custom-chains/mantaPacific.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/mantaPacific.svg
Labels: chain

#983 patch PR 1 of week ending 11/21/23
  packages/react-app-revamp/config/wagmi/custom-chains/mantaPacific.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/mantaPacific.svg
Labels: patch

#975 feat: update sorting logic frontend
  packages/react-app-revamp/components/UI/Collapsible/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Downvote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerContest/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerPlayer/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContractVersion/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: feat

#986 chain: add x1Testnet
  packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#987 patch PR 3 of week ending 11/21/23
  packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#988 feat: refactor list proposals logic and add ability to sort
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#1005 enhancement: add mona lista moustache as default avatar
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/public/contest/mona-lisa-moustache.png
Labels: enhancement

#1009 chore: update turbo to 1.10.16
  package.json
  packages/react-app-revamp/public/sw.js
  yarn.lock
Labels: chore

#1014 bugfix: add utility fn to update proposal rank
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
Labels: bugfix

#1015 patch PR 9 of week ending 11/21/23
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
Labels: patch

#1024 bugfix: call fetch proposal page in hook
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: bugfix

#1031 bugfix: only fetch proposals if more than 0 proposalIds
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: bugfix

#1030 chore: move analytics sendoff up
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: chore

#1032 patch PR 2 of week ending 11/28/23
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isUrlToImage.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: patch

#1038 enhancement: update style changes in proposal preview card
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#1039 patch PR 3 of week ending 11/28/23
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: patch

#1042 patch PR 4 of week ending 11/28/23
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/utils/error.ts
Labels: patch

#1044 bugfix: add ranks on contest load
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: bugfix

#1045 bugfix: parse proposalId to string for proposal data
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
Labels: bugfix

#1046 patch PR 5 of week ending 11/28/23
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
Labels: patch

#1022 bugfix: use without proof functions on submit and vote
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#1058 bugfix: use qToken as native currency in testnet config
  packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
Labels: bugfix

#1056 bugfix: remove contest timing reset when it is not current time
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
Labels: bugfix

#1055 bugfix: add max delay for timeout and adapt live vote
  packages/react-app-revamp/helpers/timeout.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bugfix

#1054 chore: remove lag when clicking profile submissions or votes on first load
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
Labels: chore

#1059 merge sprint ending 11/28/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
  packages/react-app-revamp/helpers/timeout.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: sprint end

#1063 chain: add holesky and redstoneHolesky
  packages/react-app-revamp/config/wagmi/custom-chains/holesky.ts
  packages/react-app-revamp/config/wagmi/custom-chains/redstoneHolesky.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain
