Repository jk-labs-inc/jokerace, pull requests merged in 2023-08, with the labels that each got.

#440 chore: resilience recovery and error catching
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/alchemy.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/404.tsx
Labels: chore

#446 test: 2 props, no votes, pay out 2nd
  packages/forge/test/RewardsModule.t.sol
Labels: test

#447 chain: add lukso
  packages/react-app-revamp/config/wagmi/custom-chains/luksoMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#448 patch PR 2 of week ending 8/1/23
  packages/forge/test/RewardsModule.t.sol
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/luksoMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/alchemy.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/404.tsx
Labels: patch

#449 chore: speed up queries for contest page and when fetching a contests
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: chore

#457 merge sprint ending 8/1/23
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: sprint end

#463 docs: update TOS
  TOS.md
Labels: documentation

#471 chain: update sepolia rpc provider
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: chain

#472 bug: remove public node fallback for alchemy chains for now
  packages/react-app-revamp/config/wagmi/index.ts
Labels: bug

#473 patch PR 3 of week ending 8/8/23
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#475 bug: added agld as native token for display and chain logo
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/lootchain.svg
Labels: bug

#474 chore: get rid of dependencies warnings
  packages/react-app-revamp/components/Clock/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotesDate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useUserBalance/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/TimelineV3/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/live/index.tsx
Labels: chore

#477 patch PR 4 of week ending 8/8/23
  packages/react-app-revamp/components/Clock/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotesDate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useTokenBalance/index.tsx
  packages/react-app-revamp/hooks/useUserBalance/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/TimelineV3/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/public/lootchain.svg
Labels: patch

#480 bug: allow opt out of deploy rewards modal and query rewards address when funding pool
  packages/react-app-revamp/components/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/store.tsx
  packages/react-app-revamp/hooks/useFundRewards/store.tsx
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
Labels: bug

#479 chain: rename chains, add linea mainnet, and add all other chain logos
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/celo.ts
  packages/react-app-revamp/config/wagmi/custom-chains/celoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gnosis.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gnosisTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/linea.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lineaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/litTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lootChainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
  packages/react-app-revamp/config/wagmi/custom-chains/luksoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantle.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mantleTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/near.ts
  packages/react-app-revamp/config/wagmi/custom-chains/nearTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetwork.ts
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zetaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zora.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/public/aurora.svg
  packages/react-app-revamp/public/celo.svg
  packages/react-app-revamp/public/evmos.svg
  packages/react-app-revamp/public/linea.svg
  packages/react-app-revamp/public/lit.svg
  packages/react-app-revamp/public/lukso.svg
  packages/react-app-revamp/public/mantle.svg
  packages/react-app-revamp/public/polygon.svg
  packages/react-app-revamp/public/zeta.svg
  packages/react-app-revamp/public/zora.png
Labels: chain

#486 chain: add mode
  packages/react-app-revamp/config/wagmi/custom-chains/modeTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#487 patch PR 1 of week ending 8/15/23
  packages/react-app-revamp/config/wagmi/custom-chains/modeTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#489 chain: add EOS
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
Labels: chain

#490 chain: add EOS pt. 2
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#491 patch PR 2 of week ending 8/15/23
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#494 bug: fix qchain symbol and explorer url and add logo
  packages/react-app-revamp/config/wagmi/custom-chains/qChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/qChainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/qchain.svg
Labels: bug

#492 feat: add workers to generate merkle tree and proof for submission/voting & create flow
  packages/react-app-revamp/components/Parameters/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/workers/generateProof.ts
  packages/react-app-revamp/workers/generateRootAndRecipients.ts
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: feat

#497 patch PR 4 for week ending 8/15/23
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetwork.ts
Labels: patch

#500 bug: fix formatting issues, refactor and organize markdown code, prevent more than 3 list items in a preview box and add custom order numbers
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownText/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: bug

#501 chore: remove change network banner in contest page, and add switch network options on submit & vote
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: chore

#502 patch PR 5 of week ending 8/15/23
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownOrderedList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownText/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: patch

#510 chain: add proteus
  packages/react-app-revamp/config/wagmi/custom-chains/proteus.ts
Labels: chain

#512 chain: add proteus pt2
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#513 patch PR 7 of week ending 8/15/23
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#506 chore: rm select stars and old contest table refs
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestsIndex/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
Labels: chore

#514 bug: reload user qualifications when acccount is changed
  packages/react-app-revamp/hooks/useAccountChange/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug

#516 patch PR 8 of week ending 8/15/23
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useAccountChange/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestsIndex/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
Labels: patch

#517 chain: add nautilus chain
  packages/react-app-revamp/config/wagmi/custom-chains/nautilusChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/nautiluschain.png
Labels: chain

#520 patch PR 1 of week ending 8/22/23
  packages/react-app-revamp/config/wagmi/custom-chains/nautilusChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/nautiluschain.png
Labels: patch

#523 chore: add eos chain logo
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/eos.svg
Labels: chore

#521 chore: extract rewards fetching from contest list process
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPlay/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
Labels: chore

#522 bug: add native token button on any chain that we support
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/public/tokens/avax.svg
  packages/react-app-revamp/public/tokens/ether.svg
  packages/react-app-revamp/public/tokens/matic.svg
Labels: bug

#524 chore: update nautilus image info
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#525 patch PR 2 of week ending 8/22/23
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPlay/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/eos.svg
  packages/react-app-revamp/public/tokens/avax.svg
  packages/react-app-revamp/public/tokens/ether.svg
  packages/react-app-revamp/public/tokens/matic.svg
Labels: patch

#526 chore: add rewards info back in list of contests for mobile
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
Labels: chore

#530 chore: update nautilus rpc endpoints to https
  packages/react-app-revamp/config/wagmi/custom-chains/nautilusChain.ts
Labels: chore

#531 patch PR 4 of week ending 8/22/23
  packages/react-app-revamp/config/wagmi/custom-chains/nautilusChain.ts
Labels: patch

#528 bug: remove customized list items in proposal and use interweave for proposals
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: bug

#533 chain: add ronin
  packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#534 patch PR 5 of week ending 8/22/23
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownList/index.tsx
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownUnorderedList/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: patch

#536 chain: scroll sepolia testnet
  packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#537 patch PR 6 of week ending 8/22/23
  packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#539 feat: add components for creator page and restyle contests page
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/schema.ts
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/SearchBar/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutCreator/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/creator/[address]/index.tsx
Labels: feat

#540 merge sprint ending 8/22/23
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/index.tsx
  packages/react-app-revamp/components/_pages/FormSearchContest/schema.ts
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/SearchBar/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutCreator/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/creator/[address]/index.tsx
Labels: sprint end

#541 bug: fix overflow for search on mobile
  packages/react-app-revamp/components/_pages/SearchBar/index.tsx
Labels: bug

#544 enhancement: connect wallet info for submit and vote CTA
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useAccountChange/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#545 enhancement: add user profile logo in header for profile and other stuff
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/pages/creator/[address]/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/etherscan.svg
  packages/react-app-revamp/public/socials/lens.svg
Labels: enhancement

#546 patch PR 1 for week ending 8/29/23
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/SearchBar/index.tsx
  packages/react-app-revamp/hooks/useAccountChange/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Contest/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/StickyCards/components/Qualifier/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/creator/[address]/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/etherscan.svg
  packages/react-app-revamp/public/socials/lens.svg
Labels: patch

#547 bug: fix classes spacing issue
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
Labels: bug

#548 bug: add prose-invert class to all prose classes
  packages/react-app-revamp/layouts/LayoutViewContest/Prompt/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/Proposal/index.tsx
Labels: bug

#550 chore: remove opensea and uniswap links
  packages/react-app-revamp/config/links/index.tsx
Labels: chore

#552 chore: rename creator page to user
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/pages/user/[address]/index.tsx
Labels: chore

#553 chore: use r2 buckets for merkle trees
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/s3/index.ts
  packages/react-app-revamp/helpers/r2.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useContestsParticipantsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/supabase_schemas/email_signups.sql
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/bucket_file_format.json
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/bucket_rules.txt
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/supabase_transfer_script.py
  packages/react-app-revamp/workers/generateProof.ts
  yarn.lock
Labels: chore

#555 chore: remove cowfund address as placeholder from CSV editors
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
Labels: chore

#554 bug: remove roots from contest store
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bug

#557 patch PR 3 for week ending 8/29/23
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#563 chore: remove merkle root calls from contracts v3
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
Labels: chore

#564 feat: add submissions page
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: feat

#568 chain: add fuse
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#569 patch PR 5 for week ending 8/29/23
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3/contracts.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#570 chore: update navigation to use link so it can use prefetch method for submissions
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: chore

#571 enhancement: add meta tags to contest page
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
Labels: enhancement

#572 merge sprint ending 8/29/23
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: sprint end

#578 chore: add fuse svg
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/public/fuse.svg
Labels: chore

#579 patch PR 1 of week ending 8/5/23
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/public/fuse.svg
Labels: patch

#582 feat: add functionality for jokerace vip programme
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/lib/vip/index.ts
  packages/react-app-revamp/supabase_schemas/user_permissions.sql
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: feat

#581 feat: add functionality for image upload and append modularity for future implementations
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/image/imgur/index.tsx
Labels: feat

#583 patch PR 2 of week ending 9/5/23
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/parseSubmissionsCsv.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/image/imgur/index.tsx
  packages/react-app-revamp/lib/vip/index.ts
  packages/react-app-revamp/supabase_schemas/user_permissions.sql
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: patch
