Repository jk-labs-inc/jokerace, pull requests merged in 2023-06, with the labels that each got.

#282 refactor: update featured contests to order list by closest date
  packages/react-app-revamp/lib/contests/index.ts
Labels: refactor

#285 merge sprint ending 6/6/23
  packages/react-app-revamp/lib/contests/index.ts
Labels: sprint end

#278 chore: add review and nomenclature to smart contracts
  README.md
  packages/forge/src/governance/Governor.sol
  packages/forge/src/governance/IGovernor.sol
  packages/forge/src/governance/extensions/GovernorCountingSimple.sol
  packages/forge/src/governance/extensions/GovernorSettings.sol
  packages/forge/src/governance/extensions/GovernorSorting.sol
  packages/forge/src/modules/RewardsModule.sol
  packages/forge/test/Contest.t.sol
  packages/forge/test/RewardsModule.t.sol
  packages/react-app-revamp/README.md
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.1.merkleVotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.3.1.merkleVotes.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#284 feat: implement new rewards in create flow
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Success/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Warning/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRewards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/DialogFundRewardsModule/Form.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Create/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/helpers/ordinalSuffix.ts
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/store.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useFundRewards/store.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/public/modal/modal_close.svg
  packages/react-app-revamp/public/toast/success.svg
  packages/react-app-revamp/public/tokens/avax.svg
  packages/react-app-revamp/public/tokens/eth.svg
  packages/react-app-revamp/public/tokens/matic.svg
  packages/react-app-revamp/public/tokens/usdc.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: feat

#289 chain: add zora chain
  packages/react-app-revamp/config/wagmi/custom-chains/zora.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#290 chore: replace jokedao twitter references with jokerace_xyz
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/pages/_app.tsx
Labels: chore

#295 patch PR 1 of sprint ending 6/27/23
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/bnbMainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lineaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zora.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/pages/_app.tsx
Labels: patch

#297 chain: add lit testnet
  packages/react-app-revamp/config/wagmi/custom-chains/litTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain
