Repository jk-labs-inc/jokerace, pull requests merged in 2023-12, with the labels that each got.

#1057 feat: refactor user store and add total votes and used votes in proposal
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: feat

#1062 bugfix: total votes available in contest incorrectly shows 0
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/SubmissionsOpen/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useSubmitters/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/store.tsx
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/index.ts
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/store.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useVoters/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/buckets/submitters/index.ts
  packages/react-app-revamp/lib/buckets/voters/index.ts
  packages/react-app-revamp/workers/fetchDataFromBucket.ts
Labels: bugfix

#1065 patch PR 2 of week ending 12/5/23
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/SubmissionsOpen/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useSubmitters/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/store.tsx
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/index.ts
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/store.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/hooks/useVoters/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/buckets/submitters/index.ts
  packages/react-app-revamp/lib/buckets/voters/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/workers/fetchDataFromBucket.ts
Labels: patch

#1067 chore: define loadFileFromBuckets inside the worker
  packages/react-app-revamp/workers/fetchDataFromBucket.ts
Labels: chore

#1068 patch PR 3 of week ending 12/5/23
  packages/react-app-revamp/workers/fetchDataFromBucket.ts
Labels: patch

#1071 patch PR 4 of week ending 12/5/23
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
Labels: patch

#1073 chore: apply style for total votes and votes cast on mobile
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
Labels: chore

#1074 patch PR 5 of week ending 12/5/23
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
Labels: patch

#1066 chore: gitignore sw.js
  .gitignore
  packages/react-app-revamp/public/sw.js
  packages/react-app-revamp/public/workbox-cf9e2b60.js
Labels: chore

#1078 chore: disable turbo caching bc we don't use it
  turbo.json
Labels: chore

#1080 chore: rm update db build warning
  yarn.lock
Labels: chore

#1089 chore: bump turbo to 1.11.0
  package.json
  yarn.lock
Labels: chore

#1095 bugfix: comments skeleton not showing
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: bugfix

#1096 patch PR 2 of week ending 12/12/23
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#1098 patch PR 3 of week ending 12/12/23
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#1101 patch PR 4 of week ending 12/12/23
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#1094 chore: fix accidentally unchanged abi import
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
Labels: chore

#1106 bugfix: remove max-height on contest-prompt
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
Labels: bugfix

#1108 patch PR 6 of week ending 12/12/23
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
Labels: patch

#1110 bugfix: eval versions correctly
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: bugfix

#1118 bugfix: use lens v2 api
  packages/react-app-revamp/config/urql/index.ts
Labels: bugfix

#1119 patch PR 8 of week ending 12/12/23
  packages/react-app-revamp/config/urql/index.ts
Labels: patch

#1115 bugfix: fix pluralization of vote count based on available votes
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
Labels: bugfix

#1107 chore: add universal profile wallet
  packages/react-app-revamp/config/wagmi/custom-wallets/luksoWallet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1105 enhancement: apply styles to mobile comment form
  packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/index.tsx
Labels: enhancement

#1104 chore: bump turbo version to 1.11.1
  package.json
  yarn.lock
Labels: chore

#1112 fmt: use double quotes
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/lib/proposal/index.ts
Labels: fmt

#1121 feat: use lens sdk
  packages/react-app-revamp/codegen.yaml
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/lens/index.ts
  packages/react-app-revamp/config/urql/index.ts
  packages/react-app-revamp/graphql/common.graphql
  packages/react-app-revamp/graphql/generated.ts
  packages/react-app-revamp/graphql/get-default-profile.graphql
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  packages/react-app-revamp/services/lens/getDefaultProfile.ts
  yarn.lock
Labels: feat

#1129 feat: add phantom wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: feat

#1130 patch PR 11 of week ending 12/12/23
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1134 chore: increase default value for allowed submissions per user
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: chore

#1133 bugfix: display comments section below voting widget in proposal on mobile
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: bugfix

#1132 enhancement: update next and prev buttons to follow proposal sort option
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: enhancement

#1135 patch PR 12 of week ending 12/12/23
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: patch

#1138 fix tweet embedding if it contains text inside link
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
Labels: bugfix

#1140 bugfix: check for lens handle
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
Labels: bugfix

#1141 patch PR 13 of week ending 12/12/23
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
Labels: patch

#1142 chore: rm accidentally left in logs
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
Labels: chore

#1143 patch PR 14 of week 12/12/23
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
Labels: patch

#1144 chain: add mode mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/mode.ts
  packages/react-app-revamp/config/wagmi/custom-chains/modeTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/mode.svg
Labels: chain

#1125 feat: implement sort on all contests
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/hooks/useSortOptions/index.ts
  packages/react-app-revamp/hooks/useSortedData/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/contests/utils/sortContests.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  yarn.lock
Labels: feat

#1145 merge sprint ending 12/12/23
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/mode.ts
  packages/react-app-revamp/config/wagmi/custom-chains/modeTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useSortOptions/index.ts
  packages/react-app-revamp/hooks/useSortedData/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/contests/utils/sortContests.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/public/mode.svg
  yarn.lock
Labels: sprint end

#1146 chore: update yarn lockfile
  yarn.lock
Labels: chore

#1152 patch PR 1 of week ending 12/19/23
  packages/react-app-revamp/components/UI/Slider/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  yarn.lock
Labels: patch

#1157 bugfix: remove error includes for metamask tx reject
  packages/react-app-revamp/utils/error.ts
Labels: bugfix

#1158 patch PR 3 of week ending 12/19/23
  packages/react-app-revamp/utils/error.ts
Labels: patch

#1179 bugfix: remove dedupe and use map instead while generating proofs
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/workers/generateProof.ts
Labels: bugfix

#1180 patch PR 5 of week ending 12/19/23
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/workers/generateProof.ts
Labels: patch

#1181 chore: rm ledger connector
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1182 patch PR 6 of week ending 12/19/23
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1184 chore: update wagmi and viem
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1185 patch PR 7 of week ending 12/19/23
  packages/react-app-revamp/components/UI/EtheuremAddress/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/eosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/fuse.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1189 chain: add astria dusk 2
  packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1190 patch PR 8 of week ending 12/19/23
  packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1196 bugfix: remove incorrect votes and rank from submission
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: bugfix

#1198 patch PR 9 of week ending 12/19/23
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: patch

#1202 chain: add neon and neonDevnet
  packages/react-app-revamp/config/wagmi/custom-chains/neon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1204 chain: update evmos rpc to avoid CORS errors
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
Labels: chain

#1206 chain: update EVMOS mainnet for CORS
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
Labels: chain

#1205 patch PR 11 of week ending 12/19/23
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/config/wagmi/custom-chains/evmosTestnet.ts
Labels: chain

#1200 chore: update rainbowkit
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1193 feat: add comments page in user profile and store comment id in analytics participants
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/user/types/index.ts
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
Labels: feat

#1208 chain: rm neon mainnet for now
  packages/react-app-revamp/config/wagmi/custom-chains/neon.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1211 chore: insert row in analytics table when proposal or comment is deleted
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useComments/store.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/user/index.tsx
Labels: chore

#1212 merge sprint ending 12/19/23
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/config/routes/index.ts
  packages/react-app-revamp/config/wagmi/custom-chains/neon.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useComments/store.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/user/types/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/public/contest/comment_icon.svg
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  yarn.lock
Labels: sprint end

#1213 chain: add frame testnet
  packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1214 patch PR 1 of week ending 12/26/23
  packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1219 bugfix: increase height of the fixed proposal preview container and fix image bug in proposal preview cards
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: bugfix

#1220 patch PR 2 of week ending 12/26/23
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: patch

#1215 chore: bump maximumFileSizeToCacheInBytes to 10mb
  packages/react-app-revamp/next.config.js
Labels: chore

#1221 chore: update style for mobile in proposal preview cards
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: chore

#1222 patch PR 3 of week ending 12/26/23
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/next.config.js
Labels: patch

#1225 chain: add fantom mainnet and testnet
  packages/react-app-revamp/config/wagmi/custom-chains/fantom.ts
  packages/react-app-revamp/config/wagmi/custom-chains/fantomTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/fantom.png
  packages/react-app-revamp/public/fantom.svg
Labels: chain

#1223 bugfix: fix broken user profile images and refactor user profile display component
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useAvatar/index.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/pages/index.tsx
Labels: bugfix

#1151 chore: invoke process user qualifications immediately after contract results
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
Labels: chore

#1233 chore: fix fantom pic
  packages/react-app-revamp/pages/_app.tsx
Labels: chore

#1229 chore: only display sort options if submissions count greater than 1
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
Labels: chore

#1234 chore: remove votes condition for voters list
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: chore

#1235 patch PR 5 of week ending 12/26/23
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/pages/_app.tsx
Labels: patch

#1245 patch PR 1 of week ending 1/2/24
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch
