Repository jk-labs-inc/jokerace, pull requests merged in 2024-05, with the labels that each got.

#1603 chain: add cyber and hedera
  packages/react-app-revamp/config/wagmi/custom-chains/cyber.ts
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1596 chore: use cloudfare bucket for image upload
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1607 enhancement: streamline contest page
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Timeline/index.tsx
Labels: enhancement

#1608 patch PR 1 of week ending 5/14/24
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Create/constants/length.ts
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/config/wagmi/custom-chains/cyber.ts
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1609 chore: hide contest description if voting is closed
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
Labels: chore

#1613 feat: frontend set split destination
  packages/react-app-revamp/components/ChargeLayout/components/CommisionDetails/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/ChargeLayout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/PercentToCreator/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
  packages/react-app-revamp/helpers/shortenEthereumAddress.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
Labels: feat

#1617 bugfix: add contest author for earnings in params tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
Labels: bugfix

#1618 patch PR 1 of week ending 5/28/24
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
Labels: patch

#1620 patch PR 2 of week ending 5/28/24
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#1622 feat: keep track of rewards tokens from supabase
  packages/react-app-revamp/components/ChargeLayout/components/CommisionDetails/index.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Error/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/PreviouslyDistributedReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/helpers/getTokenDecimals.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useRewardsTokens/usePaidRewardsTokens/index.ts
  packages/react-app-revamp/hooks/useRewardsTokens/useUnpaidRewardsTokens/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/rewards/index.ts
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
  packages/react-app-revamp/supabase_schemas/chain_params.sql
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/supabase_schemas/extensions.sql
  packages/react-app-revamp/supabase_schemas/user_permissions.sql
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#1610 chore: farcaster supports arbitrum and gnosis now
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1623 patch PR 3 of week ending 5/28/24
  packages/react-app-revamp/components/ChargeLayout/components/CommisionDetails/index.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Error/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/PreviouslyDistributedReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/helpers/getTokenDecimals.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useRewards/index.ts
  packages/react-app-revamp/hooks/useRewardsTokens/usePaidRewardsTokens/index.ts
  packages/react-app-revamp/hooks/useRewardsTokens/useUnpaidRewardsTokens/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/rewards/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/supabase_schemas/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/supabase_schemas/analytics_rewards_v3.sql
  packages/react-app-revamp/supabase_schemas/chain_params.sql
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  packages/react-app-revamp/supabase_schemas/extensions.sql
  packages/react-app-revamp/supabase_schemas/user_permissions.sql
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: patch

#1624 enhancement: update rewards info placement on mobile
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#1625 patch PR 4 of week ending 5/28/24
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: patch

#1626 chain: add taiko mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/taiko.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1627 patch PR 5 of week ending 5/28/24
  packages/react-app-revamp/config/wagmi/custom-chains/taiko.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: patch
