Repository jk-labs-inc/jokerace, pull requests merged in 2024-09, with the labels that each got.

#2266 patch PR 3 of week ending 9/3/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2264 bugfix: replace useRouter with window.location.reload for more reliable page reload
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bugfix

#2263 bugfix: remove character length for tweets in proposal preview
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isContentTweet.ts
Labels: bugfix

#2262 chore: restore proposal content visibility toggle and local storage management
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: chore

#2260 bugfix: enhance token search to prioritize symbol matches
  packages/react-app-revamp/app/api/token/route.ts
Labels: bugfix

#2267 enhancement: add rewards module address link in rewards tab
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
Labels: enhancement

#2268 patch PR 4 of week ending 9/3/24
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isContentTweet.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2288 chain: add zircuit
  packages/react-app-revamp/config/wagmi/custom-chains/zircuit.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/zircuit.png
Labels: chain

#2300 bugfix: tweets not rendering when they are paragraph element
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/helpers/isContentTweet.ts
Labels: bugfix

#2292 bugfix: hide earnings edit if percentage to creator is 0
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
Labels: bugfix

#2307 bugfix: use server config in fetch single proposal fn
  packages/react-app-revamp/hooks/useProposal/index.ts
Labels: bugfix

#2308 patch PR 2 of week ending 9/10/24
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2314 chore: update flattening script
  packages/forge/package.json
Labels: chore

#2321 feat: add cancel rewards functionality
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/hooks/useCancelRewards/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: feat

#2324 merge sprint ending 9/10/24
  packages/forge/package.json
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/hooks/useCancelRewards/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2328 bugfix: add default submissions const in store
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: bugfix

#2331 patch PR 1 of week ending 9/17/24
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: patch

#2327 bugfix: get rid of hydration error for user profile
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
Labels: bugfix

#2332 chore: rm redundant const
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#2326 chore: rm onMenuStateChange for menu component
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/NFT/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Fields/components/Field/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: bugfix

#2339 patch PR 2 of week ending 9/17/24
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/NFT/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Fields/components/Field/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2340 chore: remove frame integration
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/components/Frames/submission/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/Timing/index.tsx
  packages/react-app-revamp/components/Frames/submission/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/Frames/transactions/success/index.tsx
  packages/react-app-revamp/components/Frames/vote/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/SubmissionDeleted/index.tsx
  packages/react-app-revamp/components/Frames/vote/Timing/index.tsx
  packages/react-app-revamp/components/Frames/vote/UnsupportedChain/index.tsx
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#2341 bugfix: fix charge settings for non monetized chains
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bugfix

#2348 patch PR 2 of week ending 9/17/24
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/components/Frames/submission/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/Timing/index.tsx
  packages/react-app-revamp/components/Frames/submission/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/Frames/transactions/success/index.tsx
  packages/react-app-revamp/components/Frames/vote/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/SubmissionDeleted/index.tsx
  packages/react-app-revamp/components/Frames/vote/Timing/index.tsx
  packages/react-app-revamp/components/Frames/vote/UnsupportedChain/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2353 chain: add lamina
  packages/react-app-revamp/config/wagmi/custom-chains/lamina.ts
  packages/react-app-revamp/config/wagmi/custom-chains/laminaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/lamina.png
Labels: chain

#2355 patch PR 3 of week ending 9/17/24
  packages/react-app-revamp/config/wagmi/custom-chains/lamina.ts
  packages/react-app-revamp/config/wagmi/custom-chains/laminaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/lamina.png
  yarn.lock
Labels: patch

#2362 enhancement: improve voting slider on mobile
  packages/react-app-revamp/components/UI/Slider/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
Labels: enhancement

#2364 chore: replace placeholder color with darker grey
  packages/react-app-revamp/components/Voting/index.tsx
Labels: chore

#2366 docs: rm vercel reference
  README.md
  packages/react-app-revamp/README.md
Labels: docs

#2370 chore: add commands
  package.json
  packages/react-app-revamp/package.json
Labels: chore

#2371 feat: add nextjs build github action
  .github/workflows/nextjs_build.yml
Labels: feat

#2373 chore: rename forge tests
  .github/workflows/forge_tests.yml
Labels: chore

#2374 chore: group actions on branch
  .github/workflows/forge_tests.yml
  .github/workflows/nextjs_build.yml
Labels: chore

#2375 chore: use prod env vars if main
  .github/workflows/nextjs_build.yml
Labels: chore

#2377 chore: ignore next build files
  .gitignore
  packages/react-app-revamp/next-env.d.ts
Labels: chore

#2387 chain: add fhenix helium testnet
  packages/react-app-revamp/config/wagmi/custom-chains/fhenixHeliumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2392 chore: use popular list of tokens for token search modal
  packages/react-app-revamp/app/api/token/route.ts
Labels: chore

#2388 enhancement: increase font size for titles on landing page
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
Labels: enhancement

#2396 merge sprint ending 9/17/24
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/fhenixHeliumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2417 bugfix: add chainId to delete proposals fn
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
Labels: bugfix

#2418 patch PR 1 of week ending 9/24/24
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2432 feat: add only me option for entering the contest
  packages/react-app-revamp/components/UI/Toast/components/Info/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
Labels: feat

#2415 wording: update language for submissions
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Customization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Downvote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerContest/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerPlayer/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
Labels: wording

#2413 enhancement: prompt users to connect wallet on vote
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#2412 enhancement: update rewards analytics calculation with creator percentage
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: enhancement

#2405 enhancement: fund rewards UI/UX update
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/store.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/TokenWidgets/components/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/TokenWidgets/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/store.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/utils.ts
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
  packages/react-app-revamp/components/_pages/DialogAddFundsToRewardsModule/index.tsx
  packages/react-app-revamp/hooks/useBalance/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useTokenList/index.ts
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#2450 wording: update submission language for contests
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
Labels: wording

#2448 enhancement: remove comments toggle
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#2446 wording: apply different language for submit button on contest page for mobile
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
Labels: wording

#2447 enhancement: showcase canceled contests in the UI
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
Labels: enhancement

#2462 bugfix: fix tweet rendering issue
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: bugfix

#2449 enhancement: showcase full rewards
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasedRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsPreviouslyDistributedTable/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/hooks/useReleasableRewards/index.ts
  packages/react-app-revamp/hooks/useReleasedRewards/index.ts
  packages/react-app-revamp/lib/contests/index.ts
Labels: enhancement

#2464 patch PR 1 of week ending 10/1/24
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasableRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/ReleasedRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsPreviouslyDistributedTable/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/hooks/useReleasableRewards/index.ts
  packages/react-app-revamp/hooks/useReleasedRewards/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2469 bugfix: add voting widget to unvoted entries
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: bugfix

#2470 patch PR 2 of week ending 10/1/24
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: patch

#2499 chore: rm only me option from create flow for now
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
Labels: chore

#2500 patch PR 3 of week ending 10/1/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2477 enhancement: add different language for anyone can vote in voting widget
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#2478 enhancement: move entry collapse button to the right
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#2488 enhancement: edit info message on setting contest visibility
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/ContestVisibility/index.tsx
Labels: enhancement

#2489 enhancement: add self funding option in create flow
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#2490 enhancement: color changes
  packages/react-app-revamp/app/contests/search.tsx
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Search/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/StepCircle/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/SearchBar/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/components/Error/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#2483 chore: update voting widget placeholder to '0' instead of '0.00'
  packages/react-app-revamp/components/Voting/index.tsx
Labels: chore

#2506 chore: rm margin for collapse entry button
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
Labels: chore

#2509 chain: add boba
  packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2510 patch PR 5 of week ending 10/1/24
  packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: patch
