Repository jk-labs-inc/jokerace, pull requests merged in 2024-08, with the labels that each got.

#1995 chore: add bitget wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#2005 bugfix: improve chain support redirect in create flow
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
Labels: bugfix

#2003 chore: fix typo for berachain bartio
  packages/react-app-revamp/config/wagmi/custom-chains/berachainBartioTestnet.ts
Labels: chore

#2006 patch PR 4 of week ending 8/6/24
  package.json
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/berachainBartioTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1987 feat: add metadata fields on the frontend
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Fields/components/Field/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Fields/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/components/Fields/utils.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Metadata/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/helpers/metadata.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useMetadataFields/index.ts
  packages/react-app-revamp/hooks/useMetadataFields/store.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: feat

#2011 bugfix: add fallback for broken token images
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx
Labels: bugfix

#2025 enhancement: add karaoke challenge template
  packages/react-app-revamp/components/_pages/Create/templates/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/templates.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
Labels: enhancement

#2023 chore: apply design changes to metadata fields
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/index.tsx
  packages/react-app-revamp/helpers/metadata.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/styles/globals.css
Labels: chore

#2027 chore: rename aurora
  packages/react-app-revamp/config/wagmi/custom-chains/aurora.ts
  packages/react-app-revamp/config/wagmi/custom-chains/auroraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#2029 patch PR 1 of week ending 8/13/24
  package.json
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/templates.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/aurora.ts
  packages/react-app-revamp/config/wagmi/custom-chains/auroraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/helpers/metadata.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch

#2034 chain: add kaia aka klaytn
  packages/react-app-revamp/config/wagmi/custom-chains/kaiaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/kaia.png
Labels: chain

#2038 chore: remove truncation of the content in the submission preview
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: chore

#2064 bugfix: resolve BSOD for non-v3 contests
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/hooks/useSubmitters/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useVoters/index.ts
Labels: bugfix

#2048 enhancement: add insufficient balance per chain of the contest small design updates
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#2065 chain: add weavevm testnet
  packages/react-app-revamp/config/wagmi/custom-chains/weavevmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/wvm.svg
Labels: chain

#2067 chore: improve contest name gradient
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: chore

#2066 patch PR 3 of week ending 8/13/24
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/weavevmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useSubmitters/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useVoters/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/wvm.svg
  yarn.lock
Labels: patch

#2070 docs: update chain request form
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: documentation

#2071 chain: add forma and formaTestnet
  packages/react-app-revamp/config/wagmi/custom-chains/forma.ts
  packages/react-app-revamp/config/wagmi/custom-chains/formaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2076 bugfix: create separate components for v3 and non v3 contest prompt
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
Labels: bugfix

#2077 patch PR 4 of week ending 8/13/24
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/forma.ts
  packages/react-app-revamp/config/wagmi/custom-chains/formaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2082 chore: move metadata to description tab in create flow
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
Labels: chore

#2088 patch PR 1 of week ending 8/20/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2089 chore: update evmos rpc
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
Labels: chore

#2090 enhancement: cancel contests
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/UI/GradientText/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestState/index.ts
  packages/react-app-revamp/hooks/useContestState/store.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#2093 patch PR 2 of week ending 8/20/24
  package.json
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/UI/GradientText/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/evmos.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestState/index.ts
  packages/react-app-revamp/hooks/useContestState/store.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  yarn.lock
Labels: patch

#2094 chore: rm pinned dep
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#2107 chore: ignore react-native updates for now
  renovate.json
Labels: chore

#2114 docs: etherscan env var optional
  README.md
  packages/react-app-revamp/README.md
Labels: docs

#2124 docs: add logo to chain request
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: docs

#2132 wording: update rewards tie explanation
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
Labels: wording

#2131 chain: add kakarot sepolia
  packages/react-app-revamp/config/wagmi/custom-chains/kakarotTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/kakarot.svg
Labels: chain

#1844 feat: image processing with cloudflare workers
  .gitignore
  packages/image-processing-worker/.editorconfig
  packages/image-processing-worker/.gitignore
  packages/image-processing-worker/.prettierrc
  packages/image-processing-worker/package.json
  packages/image-processing-worker/src/index.ts
  packages/image-processing-worker/test/index.spec.ts
  packages/image-processing-worker/test/tsconfig.json
  packages/image-processing-worker/tsconfig.json
  packages/image-processing-worker/vitest.config.mts
  packages/image-processing-worker/worker-configuration.d.ts
  packages/image-processing-worker/wrangler.toml
  packages/image-processing-worker/yarn.lock
  packages/react-app-revamp/.gitignore
  packages/react-app-revamp/.vercelignore
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/contest/maximize.svg
  packages/react-app-revamp/public/contest/minimize.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: enhancement

#2137 merge sprint ending 8/20/24
  .github/ISSUE_TEMPLATE/chain_request.md
  .gitignore
  README.md
  package.json
  packages/image-processing-worker/.editorconfig
  packages/image-processing-worker/.gitignore
  packages/image-processing-worker/.prettierrc
  packages/image-processing-worker/package.json
  packages/image-processing-worker/src/index.ts
  packages/image-processing-worker/test/index.spec.ts
  packages/image-processing-worker/test/tsconfig.json
  packages/image-processing-worker/tsconfig.json
  packages/image-processing-worker/vitest.config.mts
  packages/image-processing-worker/worker-configuration.d.ts
  packages/image-processing-worker/wrangler.toml
  packages/image-processing-worker/yarn.lock
  packages/react-app-revamp/.gitignore
  packages/react-app-revamp/.vercelignore
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/UI/Markdown/components/MarkdownImage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/kakarotTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/weavevmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/contest/maximize.svg
  packages/react-app-revamp/public/contest/minimize.svg
  packages/react-app-revamp/public/kakarot.svg
  packages/react-app-revamp/public/wvm.png
  packages/react-app-revamp/public/wvm.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tsconfig.json
  renovate.json
  yarn.lock
Labels: sprint end

#2142 chore: only renovate react app revamp
  packages/image-processing-worker/package.json
  renovate.json
Labels: chore

#2141 chore: rm .vercelignore
  packages/react-app-revamp/.vercelignore
Labels: chore

#2143 chore: rm image processor lock file
  packages/image-processing-worker/yarn.lock
Labels: chore

#2145 chore: clean up package.jsons
  package.json
  packages/forge/package.json
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#2150 patch PR 1 of week ending 8/27/24
  package.json
  packages/forge/package.json
  packages/image-processing-worker/yarn.lock
  packages/react-app-revamp/.vercelignore
  packages/react-app-revamp/package.json
  renovate.json
  yarn.lock
Labels: patch

#2157 chore: preload images in proposal preview
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: chore

#2160 chore: increase max time to wait for rpc to 1 minute
  packages/react-app-revamp/helpers/timeout.ts
Labels: chore

#2159 patch PR 2 of week ending 8/27/24
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/timeout.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2161 chore: decrease wait time for rpc to 3s
  packages/react-app-revamp/helpers/timeout.ts
Labels: chore

#2162 patch PR 3 of week ending 8/27/24
  packages/react-app-revamp/helpers/timeout.ts
Labels: patch

#2166 patch PR 4 of week ending 8/27/24
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
Labels: patch

#2176 enhancement: move resize button out of image
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#2174 enhancement: improve voting UX
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/ChargeInfo/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/TotalCharge/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/index.tsx
  packages/react-app-revamp/components/ChargeLayout/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV4/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/components/TotalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/components/TotalVotesCast/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#2183 docs: add @ing david
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: docs

#2187 bugfix: fix window undefined on component load
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
Labels: bugfix

#2185 bugfix: fix scroll in template dropdown in create flow on mobile
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
Labels: bugfix

#2190 enhancement: moving up logo and wallet on landing page
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
Labels: enhancement

#2191 chain: add syscoin mainnet and testnet
  packages/react-app-revamp/config/wagmi/custom-chains/syscoin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/syscoinTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/syscoin.svg
Labels: chain

#2192 chain: add rollux mainnet and testnet
  packages/react-app-revamp/config/wagmi/custom-chains/rollux.ts
  packages/react-app-revamp/config/wagmi/custom-chains/rolluxTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/rollux.svg
Labels: chain

#2196 patch PR 6 of week ending 8/27/24
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/rollux.ts
  packages/react-app-revamp/config/wagmi/custom-chains/rolluxTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/syscoin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/syscoinTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/rollux.svg
  packages/react-app-revamp/public/syscoin.svg
  yarn.lock
Labels: patch

#2199 enhancement: add rewards at the top for mobile in contest page
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#2200 patch PR 7 of week ending 8/27/24
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2202 bugfix: fix mobile overflow for submissions
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: bugfix

#2203 patch PR 8 of week ending 8/27/24
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: patch

#2210 chore: update timeout to 10s
  packages/react-app-revamp/helpers/timeout.ts
Labels: chore

#2211 patch PR 9 of week ending 8/27/24
  packages/react-app-revamp/helpers/timeout.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2221 chain: add storyTestnet
  packages/react-app-revamp/config/wagmi/custom-chains/storyTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2222 merge sprint ending 8/27/2024
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/config/wagmi/custom-chains/storyTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2229 bugfix: quickfix rewards rounding issue
  packages/react-app-revamp/lib/rewards/index.ts
Labels: bugfix

#2231 wording: add to to votes
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
Labels: wording

#2247 chain: add soneium
  packages/react-app-revamp/config/wagmi/custom-chains/soneiumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/soneium.png
Labels: chain

#2249 patch PR 2 of week ending 9/3/24
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/soneiumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/soneium.png
  yarn.lock
Labels: patch
