Repository jk-labs-inc/jokerace, pull requests merged in 2024-11, with the labels that each got.

#2851 bugfix: unable to toggle contest visibility in profile
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
Labels: bugfix

#2867 feat: add edit title and prompt ui
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/components/EditContestName/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/components/EditContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/helpers/createEditorConfig.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useEditContestPrompt/index.ts
  packages/react-app-revamp/hooks/useEditContestTitle/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: feat

#2877 chain: update hedera img
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/public/hedera.svg
Labels: chain

#2886 chore: update chain ticket
  .github/ISSUE_TEMPLATE/chain_request.md
Labels: chore

#2884 chore: deprecate soneium testnet
  packages/react-app-revamp/config/wagmi/custom-chains/soneiumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#2889 chain: add apechain
  packages/react-app-revamp/config/wagmi/custom-chains/apechain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2888 patch PR 1 of week ending 11/12/24
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/config/wagmi/custom-chains/apechain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/config/wagmi/custom-chains/soneiumTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/hedera.svg
  yarn.lock
Labels: patch

#2933 chain: update fluent rpc and explorer url
  packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
Labels: chain

#2926 patch PR 1 of week ending 11/19/24
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/TitleLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2939 enhancement: add link icon to wallet on mobile
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/public/icons/copy.svg
Labels: enhancement

#2940 chore: update token holders message for native token
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/lib/permissioning/index.ts
Labels: chore

#2941 enhancement: set demo day as default template
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
Labels: enhancement

#2942 chore: fetch jklabs address always from db
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#2951 chain: update hedera native token decimals
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
Labels: chain

#2952 patch PR 1 of week ending 11/26/24
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/icons/copy.svg
  yarn.lock
Labels: patch

#2955 chain: update hedera rpc and decimals
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
Labels: chain

#2956 patch PR 2 of week ending 11/26/24
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
Labels: patch

#2969 patch PR 3 of week ending 11/26/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2982 feat: add dune dashboard analytics extension
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
Labels: feat

#2983 feat: add timestamp in subscribe fn
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/supabase_schemas/email_signups.sql
Labels: feat
