Repository jk-labs-inc/jokerace, pull requests merged in 2024-01, with the labels that each got.

#1246 chore: make rest of version vars strings
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContractVersion/index.ts
Labels: chore

#1228 bugfix: wrap user info and content with link in proposal preview
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: bugfix

#1230 chore: remove unused packages
  packages/react-app-revamp/package.json
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: chore

#1257 enhancement: add arbitrum chain to nft requirements
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/lib/permissioning/index.ts
Labels: enhancement

#1256 chore: update scroll logo
  packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/scroll.png
  packages/react-app-revamp/public/scroll.svg
Labels: chore

#1258 patch PR 1 of week ending 1/16/23
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Requirements/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollSepoliaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/scroll.png
  packages/react-app-revamp/public/scroll.svg
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: patch

#1260 bugfix: add onChange to input change in contest type
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
Labels: bugfix

#1261 patch PR 2 of week ending 1/16/23
  packages/react-app-revamp/components/_pages/Create/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
Labels: patch

#1263 chain: add berachain testnet
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1264 patch PR 3 of week ending 1/16/23
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1265 chain: add taiko testnet
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1266 patch PR 4 of week ending 1/16/23
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1269 chore: load submission in runtime
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useContractVersion/index.ts
  packages/react-app-revamp/hooks/useFetchProposalData/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/styles/globals.css
Labels: chore

#1270 patch PR 5 of week ending 1/16/23
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useContractVersion/index.ts
  packages/react-app-revamp/hooks/useFetchProposalData/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: patch

#1231 bugfix: clean out mobile submission page and add postcss fix lib
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/postcss.config.js
  yarn.lock
Labels: bugfix

#1272 chore: add mona lisa for missing chain logo
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/holesky.ts
  packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/proteus.ts
  packages/react-app-revamp/config/wagmi/custom-chains/redstoneHolesky.ts
  packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1273 patch PR 6 of week ending 1/16/23
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/astriaDusk2.ts
  packages/react-app-revamp/config/wagmi/custom-chains/avaxCChain.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/frameTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/holesky.ts
  packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/proteus.ts
  packages/react-app-revamp/config/wagmi/custom-chains/redstoneHolesky.ts
  packages/react-app-revamp/config/wagmi/custom-chains/ronin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/roninTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/x1Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/postcss.config.js
  yarn.lock
Labels: patch

#1277 enhancement: increase line clamp in proposal preview
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#1275 bugfix: reset file input after image upload in editor
  packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
Labels: bugfix

#1278 patch PR 1 of week ending 1/23/24
  packages/react-app-revamp/components/UI/TipTapEditorControls/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: patch

#1280 chore: switch to jokerace.io
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/pages/_app.tsx
Labels: chore

#1279 chain: add arthera mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/arthera.ts
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/arthera.svg
Labels: chain

#1281 patch PR 2 of week ending 1/23/24
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/UI/AddToHomeScreen/components/NotSupportedBrowser/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/arthera.ts
  packages/react-app-revamp/config/wagmi/custom-chains/artheraTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/public/arthera.svg
Labels: patch

#1286 chore: switch rest to io
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/pages/_app.tsx
Labels: chore

#1287 bugfix: remove padding in dialog v3 on mobile
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
Labels: bugfix

#1293 chore: apply lowercase contract address in supabase
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#1292 enhancement: add unexpected headers error in csv parse
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/helpers/csvTypes.ts
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: enhancement

#1291 enhancement: add more detailed message when no tokens found for erc721 & erc20 permissions
  packages/react-app-revamp/lib/permissioning/index.ts
Labels: enhancement

#1296 bugfix: use chain from submission requirements in contests list
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useTokenDetails/index.ts
Labels: bugfix

#1298 chain: add palm mainnet and testnet
  packages/react-app-revamp/config/wagmi/custom-chains/palm.ts
  packages/react-app-revamp/config/wagmi/custom-chains/palmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/palm.png
Labels: chain

#1301 patch PR 1 of week ending 1/30/24
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/palm.ts
  packages/react-app-revamp/config/wagmi/custom-chains/palmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useTokenDetails/index.ts
  packages/react-app-revamp/public/palm.png
Labels: patch

#1304 chain: add lyra chain
  packages/react-app-revamp/config/wagmi/custom-chains/lyra.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/lyra.svg
Labels: chain

#1305 patch PR 2 of week ending 1/30/24
  packages/react-app-revamp/config/wagmi/custom-chains/lyra.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/lyra.svg
Labels: patch

#1308 chore: catch up bytecode
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.22.refactorDistributionFunc.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.22.refactorDistributionFunc.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#1309 chore: add flattened files to flow
  packages/forge/package.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.22.refactorDistributionFunc.sol/flattenedContest.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/flattenedContest.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.22.refactorDistributionFunc.sol/flattenedRewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/flattenedRewardsModule.sol
Labels: chore

#1306 bugfix: use name or symbol for token details in params tab
  packages/react-app-revamp/hooks/useTokenDetails/index.ts
Labels: bugfix
