Repository jk-labs-inc/jokerace, pull requests merged in 2024-02, with the labels that each got.

#1310 feat: implement cost to vote charge on frontend
  packages/react-app-revamp/components/ChargeLayout/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Charge/components/PercentToCreator/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Charge/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/Charge/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/EntryCharge/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useEntryChargeDetails/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/supabase_schemas/chain_params.sql
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: feat

#1276 chain: rm pgn
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetwork.ts
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/publicgoodsnetwork.svg
Labels: chain

#1312 chain: update taiko testnet
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
Labels: chain

#1313 patch PR 3 of week ending 1/30/24
  packages/forge/package.json
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetwork.ts
  packages/react-app-revamp/config/wagmi/custom-chains/publicGoodsNetworkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.22.refactorDistributionFunc.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.4.22.refactorDistributionFunc.sol/flattenedContest.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.sol/flattenedContest.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.22.refactorDistributionFunc.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.22.refactorDistributionFunc.sol/flattenedRewardsModule.sol
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/flattenedRewardsModule.sol
  packages/react-app-revamp/hooks/useTokenDetails/index.ts
  packages/react-app-revamp/public/publicgoodsnetwork.svg
Labels: patch

#1315 chain: update taiko testnet chain id
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
Labels: chain

#1316 patch PR 2 of week ending 2/6/24
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
Labels: patch

#1317 chore: add logo for taiko chain
  packages/react-app-revamp/config/wagmi/custom-chains/taikoTestnet.ts
  packages/react-app-revamp/public/taiko.svg
Labels: chore

#1324 chain: add fraxal mainnet and testnet
  packages/react-app-revamp/config/wagmi/custom-chains/fraxtal.ts
  packages/react-app-revamp/config/wagmi/custom-chains/fraxtalTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/fraxtal.svg
Labels: chain

#1325 patch PR 1 of week ending 2/23/24
  packages/react-app-revamp/config/wagmi/custom-chains/fraxtal.ts
  packages/react-app-revamp/config/wagmi/custom-chains/fraxtalTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/fraxtal.svg
Labels: patch

#1326 bugfix: remove decimal check from number input
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
Labels: bugfix

#1331 chain: add aevo
  packages/react-app-revamp/config/wagmi/custom-chains/aevo.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/aevo.svg
Labels: chain

#1333 chain: add sei
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/sei.svg
Labels: chain

#1334 patch PR 1 of week ending 2/20/24
  packages/react-app-revamp/config/wagmi/custom-chains/aevo.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/aevo.svg
  packages/react-app-revamp/public/sei.svg
Labels: patch

#1340 chain: add syndicate frame
  packages/react-app-revamp/config/wagmi/custom-chains/syndicateFrame.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1342 bugfix: add percentage to creator value for vote cast analytics
  packages/react-app-revamp/hooks/useCastVotes/index.ts
Labels: bugfix

#1344 patch PR 2 of week ending 2/20/24
  packages/react-app-revamp/config/wagmi/custom-chains/syndicateFrame.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
Labels: patch

#1351 bugfix: add type base64 to body in imgur api
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/image/imgur/index.tsx
Labels: bugfix

#1352 patch PR 4 of week ending 2/20/24
  packages/react-app-revamp/hooks/useUploadImage/index.tsx
  packages/react-app-revamp/lib/image/imgur/index.tsx
Labels: patch

#1353 chore: rm cloning coming soon for now
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
Labels: chore

#1354 patch PR 5 of week ending 2/20/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
Labels: patch

#1355 chore: update tagline and capitalization
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/manifest.json
Labels: chore

#1357 merge sprint ending 2/20/24
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/pages/404.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/public/manifest.json
Labels: sprint end

#1360 bugfix: fix typo on timing in confirmation page
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
Labels: bugfix

#1361 chore: correct sei native token
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
Labels: chore

#1362 patch PR 1 of week ending 2/27/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
Labels: patch

#1363 chain: add morph testnet
  packages/react-app-revamp/config/wagmi/custom-chains/morphTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/morph.svg
Labels: chain

#1364 chain: add berachain svg
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/public/berachain.svg
Labels: chain

#1365 patch PR 2 of week ending 2/27/24
  packages/react-app-revamp/config/wagmi/custom-chains/berachainTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/morphTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/berachain.svg
  packages/react-app-revamp/public/morph.svg
Labels: patch

#1367 bugfix: fix list item in confirmation page
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
Labels: bugfix

#1374 chain: add blast testnet
  packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1375 patch PR 3 of week ending 2/27/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Submitters/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1377 chain: add ancient 8 testnet and mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/ancient8.ts
  packages/react-app-revamp/config/wagmi/custom-chains/ancient8Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1378 patch PR 4 of week ending 2/27/24
  packages/react-app-revamp/config/wagmi/custom-chains/ancient8.ts
  packages/react-app-revamp/config/wagmi/custom-chains/ancient8Testnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1366 feat: finish up major items for create flow
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/NFT/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/Token/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/components/CSVUploadSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/Token/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/csvTypes.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/hooks/useTokenList/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/api/token/token.ts
  packages/react-app-revamp/public/create-flow/copy.svg
  packages/react-app-revamp/public/create-flow/search.svg
  packages/react-app-revamp/public/mainnet.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
  yarn.lock
Labels: feat

#1384 merge sprint ending 2/27/24
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/NFT/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/components/Token/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/Token/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/components/CSVUploadSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/CSVParseError/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableBody/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/Token/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/csvTypes.ts
  packages/react-app-revamp/helpers/parseVotingCsv.ts
  packages/react-app-revamp/helpers/regex.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/hooks/useTokenList/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/api/token/token.ts
  packages/react-app-revamp/public/create-flow/copy.svg
  packages/react-app-revamp/public/create-flow/search.svg
  packages/react-app-revamp/public/mainnet.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/workers/parseSubmissionCsv.ts
  packages/react-app-revamp/workers/parseVotingCsv.ts
  yarn.lock
Labels: sprint end

#1385 chore: reduce number of tokens in user list and update logo
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/public/jokerace.jpg
  packages/react-app-revamp/public/jokerace.png
Labels: chore

#1386 patch PR 1 of week ending 3/5/24
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/public/jokerace.jpg
  packages/react-app-revamp/public/jokerace.png
Labels: patch

#1389 chore: remove limit on user tokens in token selection modal
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
Labels: chore

#1390 patch PR 2 of week ending 3/5/24
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
Labels: patch

#1396 chore: remove walletconnect and coinbase wallet, set ssr to false
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1397 patch PR 4 of week ending 3/5/24
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch
