Repository jk-labs-inc/jokerace, pull requests merged in 2024-06, with the labels that each got.

#1632 chore: add retro funding config
  funding.json
Labels: chore

#1634 bugfix: resolve checksum issues for contest addresses in db
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/analytics/participants/index.ts
  packages/react-app-revamp/lib/analytics/rewards/index.ts
  packages/react-app-revamp/lib/contests/index.ts
Labels: bugfix

#1636 chain: add ham chain
  packages/react-app-revamp/config/wagmi/custom-chains/ham.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1637 patch PR 2 of week ending 6/11/24
  packages/react-app-revamp/config/wagmi/custom-chains/ham.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: patch

#1639 chain: add berachain bArtio testnet
  packages/react-app-revamp/config/wagmi/custom-chains/berachainBartioTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1642 enhancement: clarify my votes for anyone can vote on contest page
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
Labels: enhancement

#1643 chore: clarify pay per vote vs per tx in params tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
Labels: chore

#1644 feat: add clusters in the user profile
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/socials/cluster.png
  yarn.lock
Labels: feat

#1648 patch PR 2 of week ending 6/18/24
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
Labels: patch

#1650 chore: adjust withdraw and distribute in rewards module and fix few bugs
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/PayeeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/rewards/index.ts
Labels: chore

#1651 patch PR 3 of week ending 6/18/24
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawERC20Reward.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdrawNativeReward.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/ERC20Reward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/PayeeReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/Reward/components/DistributableReward/index.tsx
  packages/react-app-revamp/components/_pages/RewardsDistributionTable/components/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/hooks/useDistributeRewards/index.tsx
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/rewards/index.ts
Labels: patch

#1655 chore: use alchemy for sepolia rpc
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: chore

#1656 patch PR 4 of week ending 6/18/24
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: patch

#1657 chore: format rewards balance in contest info
  packages/react-app-revamp/lib/contests/index.ts
Labels: chore

#1658 patch PR 5 of week ending 6/18/24
  packages/react-app-revamp/lib/contests/index.ts
Labels: patch

#1661 chore: add media kit link in the footer
  packages/react-app-revamp/app/page.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: chore

#1663 chore: update test solidity version
  packages/forge/test/Contest.t.sol
  packages/forge/test/RewardsModule.t.sol
Labels: chore

#1665 merge sprint ending 6/18/24
  packages/forge/package.json
  packages/forge/test/Contest.t.sol
  packages/forge/test/RewardsModule.t.sol
Labels: sprint end

#1667 chore: rm unused package-lock file
  packages/react-app-revamp/package-lock.json
Labels: chore

#1668 chore: update dependencies
  package.json
  packages/react-app-revamp/package.json
  turbo.json
  yarn.lock
Labels: chore

#1670 chore: rm rest of carats
  package.json
  packages/forge/package.json
  yarn.lock
Labels: chore

#1671 chore: rm yarn install warning
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1669 patch PR 1 of week ending 6/25/24
  package.json
  packages/forge/package.json
  packages/react-app-revamp/package-lock.json
  packages/react-app-revamp/package.json
  turbo.json
  yarn.lock
Labels: patch

#1674 chain: add goerli back
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1675 patch PR 2 of week ending 6/25/24
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: patch

#1676 enhancement: add stack extension
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Stack/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
Labels: enhancement

#1677 feat: templates pt2
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/MobileStepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/templates.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/helpers/enum.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: feat

#1678 merge sprint ending 6/25/24
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Stack/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/MobileStepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/templates.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/helpers/enum.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: sprint end

#1681 chore: adjust play and create buttons
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPlay/index.tsx
Labels: chore

#1682 patch PR 1 of week ending 7/2/24
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPlay/index.tsx
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
Labels: patch

#1705 patch 2 of week ending 7/2/24
  package.json
  packages/react-app-revamp/package.json
  renovate.json
  yarn.lock
Labels: patch

#1712 chore: revert #1664 and change to +3 with latest foundryup
  packages/forge/package.json
Labels: chore

#1725 chore: change sei chain id
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
Labels: chore

#1723 enhancement: submission preview redesign
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/public/contest/upvote.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#1729 patch 4 of week ending 7/2/24
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/public/contest/upvote.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: patch

#1737 patch PR 5 of week ending 7/2/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1739 chain: add sei testnet
  packages/react-app-revamp/config/wagmi/custom-chains/seiTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1740 chore: update sei rpc to mainnet
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
Labels: chore

#1748 chore: add minor and patch automerge
  renovate.json
Labels: chore

#1751 chore: make automerge squashed
  renovate.json
Labels: chore

#1753 chore: add comma
  renovate.json
Labels: chore
