Repository jk-labs-inc/jokerace, pull requests merged in 2024-12, with the labels that each got.

#3012 chore: make all rpc calls resilient to failure
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: chore

#3003 feat: redesigned description page with image upload
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Create/components/PromptPreview/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/PromptPreviewToggle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageAndTitleLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
Labels: feat

#3013 merge sprint ending 12/3/24
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/EntryPreviewTitleToggle/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/EntryPreviewTitleToggle/store.ts
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/PromptPreview/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/PromptPreviewToggle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestEntries/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageAndTitleLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/metadata.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: sprint end

#3020 chore: turn off live updates
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: chore

#3027 wording: update allowlist wording to present tense
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
Labels: wording

#3028 patch PR 1 of week ending 12/10/24
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/SubmissionQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/extensions/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/supabase_schemas/extensions.sql
  yarn.lock
Labels: patch

#3029 chore: revert to 2 images per row in gallery layout
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
Labels: chore

#3030 patch PR 2 of week ending 12/10/24
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
Labels: patch

#3000 chore: rm leftover chains
  packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/kaiaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#3035 bugfix: fix metadata for contest link
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
Labels: bugfix

#3043 feat: add bridge docs when user doesn't have funds
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: feat

#3044 bugfix: fix voting close functionality in timing tab of create flow
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
Labels: bugfix

#3045 patch PR 3 of week ending 12/10/24
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/fluentTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/kaiaTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3064 enhancement: add better transition for numbers in rewards pool
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#3063 chore: disable decimals in create pool
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
Labels: chore

#3062 bugfix: maintain scroll position when page routing
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
Labels: bugfix

#3065 patch PR 1 of week ending 12/17/24
  .github/ISSUE_TEMPLATE/chain_request.md
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/TotalRewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: patch

#3068 chore: remove expand all on mobile
  packages/react-app-revamp/components/_pages/Contest/components/EntryPreviewTitleToggle/index.tsx
Labels: chore

#3085 patch PR 2 of week ending 12/17/24
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/ChargeInfo/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/TotalCharge/index.tsx
  packages/react-app-revamp/components/UI/Slider/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/EntryPreviewTitleToggle/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3097 bugfix: fix contract version not found err
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
Labels: bugfix

#3098 chore: remove logging
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/hooks/useEditContestTitleAndImage/index.tsx
Labels: chore

#3099 enhancement: add link in toast to bridge docs
  packages/react-app-revamp/components/UI/Toast/components/Info/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#3106 enhancement: improve leaderboard spacing
  packages/react-app-revamp/components/_pages/ProposalContent/components/Profile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
Labels: enhancement

#3109 chore: revert tailwind scrollbar hide package
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3110 patch PR 2 of week ending 12/24/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3128 enhancement: add blur container to contest image
  packages/react-app-revamp/components/_pages/Contest/components/ContestImage/index.tsx
Labels: enhancement

#3129 chore: remove recommended px info from image upload
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/components/EditContestName/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/UploadImage/index.tsx
Labels: chore

#3130 patch PR 3 of week ending 12/24/24
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestImage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/components/EditContestName/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/UploadImage/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/bnb.png
  yarn.lock
Labels: patch

#3131 chore: update toast language for execution reverted errors
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/utils/error.ts
Labels: chore

#3138 patch PR 4 of week ending 12/24/24
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/utils/error.ts
  yarn.lock
Labels: patch

#3145 chore: update toast error functionality
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/utils/error.ts
Labels: chore

#3146 patch PR 1 of week ending 12/31/24
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/utils/error.ts
  yarn.lock
Labels: patch
