Repository jk-labs-inc/jokerace, pull requests merged in 2024-07, with the labels that each got.

#1773 patch PR 7 of week ending 7/2/24
  .github/workflows/auto_rebase_main_PRs.yml
  .github/workflows/forge_tests.yml
  Dockerfile
  package.json
  packages/react-app-revamp/package.json
  renovate.json
  yarn.lock
Labels: patch

#1772 enhancement: add show / hide toggle for submissions
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#1781 merge sprint ending 7/2/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#1790 docs: update README
  README.md
Labels: documentation

#1802 patch PR 1 of week ending 7/9/24
  README.md
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Search/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/component/Nft/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/SearchInput/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/UI/Collapsible/index.tsx
  packages/react-app-revamp/components/UI/ConnectButton/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/FormField/index.tsx
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/FileUpload/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentInfo/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch

#1816 chain: add metis
  packages/react-app-revamp/config/wagmi/custom-chains/metis.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/metis.svg
Labels: chain

#1818 chore: husky install deprecated
  package.json
Labels: chore

#1815 chore: adapt HeadlessUI v2 api
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/UI/Deployment/Ethereum/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/ToggleSwitch/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
Labels: chore

#1832 feat: add farcaster share button
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/public/socials/farcaster-light.svg
  packages/react-app-revamp/public/socials/farcaster.svg
  packages/react-app-revamp/public/socials/lens-light.svg
  packages/react-app-revamp/public/socials/share-submission/farcaster.svg
Labels: feat

#1833 merge sprint ending 7/9/24
  package.json
  packages/react-app-revamp/app/portal.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/UI/AddToHomeScreen/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/UI/Deployment/Ethereum/index.tsx
  packages/react-app-revamp/components/UI/DialogModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/TipTapEditorControls/components/Dropdown/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/UI/ToggleSwitch/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/SortDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/metis.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/helpers/copyToClipboard.ts
  packages/react-app-revamp/helpers/share.ts
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/metis.svg
  packages/react-app-revamp/public/socials/farcaster-light.svg
  packages/react-app-revamp/public/socials/farcaster.svg
  packages/react-app-revamp/public/socials/lens-light.svg
  packages/react-app-revamp/public/socials/share-submission/farcaster.svg
  yarn.lock
Labels: sprint end

#1849 chore: revert #1809
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/getBlock.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/workers/generateProof.ts
  yarn.lock
Labels: chore

#1838 enhancement: rewards flow tweaks
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
Labels: enhancement

#1845 enhancement: confirmation page
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
Labels: enhancement

#1848 enhancement: rm read more when voting opened or closed
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
Labels: enhancement

#1850 patch PR 2 of week ending 7/16/24
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/AddTokenWidget/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/Legacy/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
Labels: patch

#1861 patch PR 2 of week ending 7/16/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1879 patch PR 1 of week ending 7/23/24
  package.json
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1904 chore: update cyber logo
  packages/react-app-revamp/config/wagmi/custom-chains/cyber.ts
  packages/react-app-revamp/public/cyber.svg
Labels: chore

#1911 merge sprint ending 7/23/24
  package.json
  packages/react-app-revamp/config/wagmi/custom-chains/cyber.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/cyber.svg
  yarn.lock
Labels: sprint end

#1916 chore: rm deprecated dependency
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1917 chore: delete breaking husky line
  .husky/post-checkout
Labels: chore

#1947 patch PR 1 of week ending 7/30/24
  .husky/post-checkout
  package.json
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1950 chain: add movement testnet
  packages/react-app-revamp/config/wagmi/custom-chains/movement.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/movement.svg
Labels: chain

#1952 patch PR 2 of week ending 7/30/24
  package.json
  packages/react-app-revamp/config/wagmi/custom-chains/movement.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/movement.svg
  yarn.lock
Labels: patch

#1954 chore: update movement testnet filename
  packages/react-app-revamp/config/wagmi/custom-chains/movementTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#1958 chain: add sanko
  packages/react-app-revamp/config/wagmi/custom-chains/sanko.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/sanko.png
Labels: chain

#1959 bugfix: lowercase chain name when fetching votes balance
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
Labels: bugfix

#1962 patch PR 3 of week ending 7/30/24
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/movementTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sanko.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/sanko.png
  yarn.lock
Labels: patch

#1922 enhancement: new landing page
  packages/react-app-revamp/app/contest/new/page.tsx
  packages/react-app-revamp/app/page.tsx
  packages/react-app-revamp/components/Explainer/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/UI/ConnectButton/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/UsedBy/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/used-by/arbitrum.svg
  packages/react-app-revamp/public/used-by/boysclub.svg
  packages/react-app-revamp/public/used-by/eigenlayer.svg
  packages/react-app-revamp/public/used-by/ethdenver.svg
  packages/react-app-revamp/public/used-by/ethfoundation.svg
  packages/react-app-revamp/public/used-by/megaeth.svg
  packages/react-app-revamp/public/used-by/polygon.svg
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: enhancement

#1961 feat: add logic to fetch jk labs split destination address during deployment
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: feat

#1965 chore: update avalanche chain name
  packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#1967 chore: remove animate reveal on featured contest card
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
Labels: chore

#1968 patch PR 1 of week ending 8/6/24
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1977 chore: user profile page optimizations
  packages/react-app-revamp/app/user/[address]/comments/page.tsx
  packages/react-app-revamp/app/user/[address]/submissions/page.tsx
  packages/react-app-revamp/app/user/[address]/votes/page.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/Skeleton/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/user/index.tsx
Labels: chore

#1979 patch PR 2 of week ending 8/6/24
  package.json
  packages/react-app-revamp/app/user/[address]/comments/page.tsx
  packages/react-app-revamp/app/user/[address]/submissions/page.tsx
  packages/react-app-revamp/app/user/[address]/votes/page.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/Skeleton/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1980 bugfix: use query instead of match for user profiles
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/lib/user/index.tsx
Labels: bugfix

#1981 patch PR 3 of week ending 8/6/24
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/lib/user/index.tsx
Labels: patch
