Repository jk-labs-inc/jokerace, pull requests merged in 2024-04, with the labels that each got.

#1514 chain: add camp
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/camp.png
Labels: chain

#1515 patch PR 1 of week ending 4/9/24
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/camp.png
Labels: patch

#1517 chain: add gold
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gold.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1518 patch PR 2 of week ending 4/9/24
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gold.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#1519 chore: add safe wallet
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1520 chain: add gold logo
  packages/react-app-revamp/public/gold.png
Labels: chain

#1521 patch PR 3 of week ending 4/9/24
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/gold.png
Labels: patch

#1522 chore: add missing chains
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#1524 chore: rename favicon
  packages/react-app-revamp/app/icon.ico
Labels: chore

#1525 patch PR 5 of week ending 4/9/24
  packages/react-app-revamp/app/icon.ico
Labels: patch

#1527 chore: update base sepolia id
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
Labels: chore

#1528 merge sprint ending 4/9/24
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
Labels: sprint end

#1533 chain: add fhenix testnet
  packages/react-app-revamp/config/wagmi/custom-chains/fhenix.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/fhenix.svg
Labels: chain

#1534 chain: add xlayer
  packages/react-app-revamp/config/wagmi/custom-chains/xLayer.ts
  packages/react-app-revamp/config/wagmi/custom-chains/xLayerTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#1536 patch PR 1 of week ending 4/16/24
  packages/react-app-revamp/config/wagmi/custom-chains/fhenix.ts
  packages/react-app-revamp/config/wagmi/custom-chains/xLayer.ts
  packages/react-app-revamp/config/wagmi/custom-chains/xLayerTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/fhenix.svg
Labels: patch

#1537 chore: fix xLayer order
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chore

#1538 chore: circularize sei logo
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
  packages/react-app-revamp/public/sei.png
  packages/react-app-revamp/public/sei.svg
Labels: chore

#1539 patch PR 2 of week ending 4/15/24
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/sei.png
  packages/react-app-revamp/public/sei.svg
Labels: patch

#1535 feat: add frames logic
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/helpers/shortenEthereumAddress.ts
  packages/react-app-revamp/helpers/shortenProposalId.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: feat

#1532 feat: add extensions
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/Card/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Bello/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Coinvise/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Nance/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/types.ts
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/hooks/useBello/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useExtensions/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/extensions/index.ts
  packages/react-app-revamp/supabase_schemas/extensions.sql
Labels: feat

#1541 chore: clean up build
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1540 merge sprint ending 4/16/24
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/Card/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Bello/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Coinvise/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Nance/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/types.ts
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/helpers/shortenEthereumAddress.ts
  packages/react-app-revamp/helpers/shortenProposalId.ts
  packages/react-app-revamp/hooks/useBello/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useExtensions/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/extensions/index.ts
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/ui.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/supabase_schemas/extensions.sql
  packages/react-app-revamp/tsconfig.json
  yarn.lock
Labels: sprint end

#1542 chore: add frame metadata
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
Labels: chore

#1543 patch PR 1 of week ending 4/23/24
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
Labels: patch

#1544 chore: add opengraph and twitter img to contest routes
  packages/react-app-revamp/app/contest/[chain]/[address]/opengraph-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/opengraph-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/twitter-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/twitter-image.jpg
Labels: chore

#1545 patch PR 2 of week ending 4/23/24
  packages/react-app-revamp/app/contest/[chain]/[address]/opengraph-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/opengraph-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/twitter-image.jpg
  packages/react-app-revamp/app/contest/[chain]/[address]/twitter-image.jpg
Labels: patch

#1549 chore: add ENS support for frames
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
Labels: chore

#1548 chore: adjust frame urls and small style change
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
Labels: chore

#1550 patch PR 3 of week ending 4/23/24
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
Labels: patch

#1554 chore: reorganize frames code
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/components/Frames/submission/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/Timing/index.tsx
  packages/react-app-revamp/components/Frames/submission/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/Frames/transactions/success/index.tsx
  packages/react-app-revamp/components/Frames/vote/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/SubmissionDeleted/index.tsx
  packages/react-app-revamp/components/Frames/vote/Timing/index.tsx
  packages/react-app-revamp/components/Frames/vote/UnsupportedChain/index.tsx
Labels: chore

#1555 patch PR 4 of week ending 4/23/24
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
  packages/react-app-revamp/components/Frames/submission/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/submission/Timing/index.tsx
  packages/react-app-revamp/components/Frames/submission/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/Frames/transactions/success/index.tsx
  packages/react-app-revamp/components/Frames/vote/Allowlisted/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/InitialFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/SubmissionDeleted/index.tsx
  packages/react-app-revamp/components/Frames/vote/Timing/index.tsx
  packages/react-app-revamp/components/Frames/vote/UnsupportedChain/index.tsx
Labels: patch

#1556 chore: rm pwa browser popup for now
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: chore

#1557 patch PR 5 of week ending 4/23/24
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: patch

#1559 enhancement: add check for frame date in secondary step too
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
Labels: enhancement

#1560 patch PR 6 of week ending 4/23/24
  packages/react-app-revamp/app/api/[[...routes]]/route.tsx
Labels: patch

#1561 chore: update lens packages
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1565 bugfix: fix submitters and voters info in params tab
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: bugfix

#1566 chore: update hats link
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
Labels: chore

#1567 patch PR 8 of week ending 4/23/24
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/HatsProtocol/index.tsx
Labels: patch

#1568 enhancement: apply brighter mona lisa
  packages/react-app-revamp/app/icon.ico
  packages/react-app-revamp/public/contest/mona-lisa-moustache.png
Labels: enhancement

#1570 enhancement: create contest on mobile
  packages/react-app-revamp/components/ChargeLayout/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: enhancement

#1571 merge sprint ending 4/23/24
  packages/react-app-revamp/app/icon.ico
  packages/react-app-revamp/components/ChargeLayout/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DefaultDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionTabMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestType/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabContent/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingTabMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/public/contest/mona-lisa-moustache.png
Labels: sprint end

#1575 chore: use icon as png
  packages/react-app-revamp/app/icon.ico
  packages/react-app-revamp/app/icon.png
Labels: chore

#1576 patch PR 1 of week ending 4/30/24
  packages/react-app-revamp/app/icon.ico
  packages/react-app-revamp/app/icon.png
Labels: patch

#1578 chore: fix language in voting widget
  packages/react-app-revamp/components/ChargeLayout/components/Vote/index.tsx
Labels: chore

#1577 chore: apply eth -> lens -> address order for user profile
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/lib/frames/submission/index.ts
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/lib/frames/voting/index.ts
Labels: chore

#1583 enhancement: apply min-width to tweet container
  packages/react-app-revamp/styles/globals.css
Labels: enhancement

#1584 patch PR 3 of week ending 4/30/24
  packages/react-app-revamp/styles/globals.css
Labels: patch

#1587 chore: update email input wording
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
Labels: chore

#1585 bugfix: remove timing conditionals from cost to submit and vote in useContest
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: bugfix

#1582 chore: implement race condition in getEnsAvatar fn
  packages/react-app-revamp/hooks/useProfileData/index.ts
Labels: chore

#1581 bugfix: fix error in voting invalid entries modal
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: bugfix

#1588 patch PR 4 of week ending 4/30/24
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/styles/globals.css
  packages/react-app-revamp/workers/parseVotingCsv.ts
Labels: patch

#1589 chore: add degen chain support in frames
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1590 patch PR 5 of week ending 4/30/24
  packages/react-app-revamp/components/Frames/submission/FinalFrame/index.tsx
  packages/react-app-revamp/components/Frames/vote/FinalFrame/index.tsx
  packages/react-app-revamp/lib/frames/utils.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch
