Repository jk-labs-inc/jokerace, pull requests merged in 2024-10, with the labels that each got.

#2515 enhancement: add textarea in metadata string fields
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
Labels: enhancement

#2517 merge sprint ending 10/1/24
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2527 bugfix: set max submissions per contest const to be 10,000
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bugfix

#2532 bugfix: fix downvote ui
  packages/react-app-revamp/components/Voting/index.tsx
Labels: bugfix

#2539 bugfix: revert "fix(deps): update dependency @tanstack/react-query to…
  packages/react-app-revamp/package.json
  yarn.lock
Labels: bugfix

#2542 patch PR 3 of week ending 10/8/24
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2540 chore: set up renovate scheduling
  renovate.json
Labels: chore

#2552 enhancement: apply wallet/profile switch for mobile
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/MobileWalletPortal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#2550 chain: add zetachain
  packages/react-app-revamp/config/wagmi/custom-chains/zeta.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2544 wording: update limit wording
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
Labels: wording

#2549 chain: add plume testnet
  packages/react-app-revamp/config/wagmi/custom-chains/plumeTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/plume.svg
Labels: chain

#2554 patch PR 5 of week ending 10/8/24
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/MobileWalletPortal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/plumeTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zeta.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/plume.svg
Labels: patch

#2497 chore: move to quicknode
  .github/workflows/nextjs_build.yml
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: chore

#2558 patch PR 6 of week ending 10/8/24
  .github/workflows/nextjs_build.yml
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/mainnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZkTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: patch

#2590 chore: disable caching for all api get routes
  packages/react-app-revamp/app/api/bucket/load/route.ts
  packages/react-app-revamp/app/api/contest-exists/route.ts
  packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
  packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
  packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
  packages/react-app-revamp/app/api/contest/requirements-data/route.ts
  packages/react-app-revamp/app/api/contests/featured/route.ts
  packages/react-app-revamp/app/api/contests/live/route.ts
  packages/react-app-revamp/app/api/contests/participant-data/route.ts
  packages/react-app-revamp/app/api/contests/past/route.ts
  packages/react-app-revamp/app/api/contests/search/route.ts
  packages/react-app-revamp/app/api/contests/upcoming/route.ts
  packages/react-app-revamp/app/api/extensions/route.ts
  packages/react-app-revamp/app/api/monetization/charge-details/route.ts
  packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
  packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
  packages/react-app-revamp/app/api/user/comments/route.ts
  packages/react-app-revamp/app/api/user/contests/route.ts
  packages/react-app-revamp/app/api/user/submissions/route.ts
Labels: chore

#2563 bugfix: fix load more button not appearing for entry voters list
  packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: bugfix

#2597 patch PR 7 of week ending 10/8/24
  packages/react-app-revamp/app/api/bucket/load/route.ts
  packages/react-app-revamp/app/api/contest-exists/route.ts
  packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
  packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
  packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
  packages/react-app-revamp/app/api/contest/requirements-data/route.ts
  packages/react-app-revamp/app/api/contests/featured/route.ts
  packages/react-app-revamp/app/api/contests/live/route.ts
  packages/react-app-revamp/app/api/contests/participant-data/route.ts
  packages/react-app-revamp/app/api/contests/past/route.ts
  packages/react-app-revamp/app/api/contests/search/route.ts
  packages/react-app-revamp/app/api/contests/upcoming/route.ts
  packages/react-app-revamp/app/api/extensions/route.ts
  packages/react-app-revamp/app/api/monetization/charge-details/route.ts
  packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
  packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
  packages/react-app-revamp/app/api/user/comments/route.ts
  packages/react-app-revamp/app/api/user/contests/route.ts
  packages/react-app-revamp/app/api/user/submissions/route.ts
  packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2600 chore: replace dynamic with force-no-store
  packages/react-app-revamp/app/api/bucket/load/route.ts
  packages/react-app-revamp/app/api/contest-exists/route.ts
  packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
  packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
  packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
  packages/react-app-revamp/app/api/contest/requirements-data/route.ts
  packages/react-app-revamp/app/api/contests/featured/route.ts
  packages/react-app-revamp/app/api/contests/live/route.ts
  packages/react-app-revamp/app/api/contests/participant-data/route.ts
  packages/react-app-revamp/app/api/contests/past/route.ts
  packages/react-app-revamp/app/api/contests/search/route.ts
  packages/react-app-revamp/app/api/contests/upcoming/route.ts
  packages/react-app-revamp/app/api/extensions/route.ts
  packages/react-app-revamp/app/api/monetization/charge-details/route.ts
  packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
  packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
  packages/react-app-revamp/app/api/user/comments/route.ts
  packages/react-app-revamp/app/api/user/contests/route.ts
  packages/react-app-revamp/app/api/user/submissions/route.ts
Labels: chore

#2602 patch PR 8 of week ending 10/8/24
  packages/react-app-revamp/app/api/bucket/load/route.ts
  packages/react-app-revamp/app/api/contest-exists/route.ts
  packages/react-app-revamp/app/api/contest/check-allowlist-permission/route.ts
  packages/react-app-revamp/app/api/contest/get-details-by-address/route.ts
  packages/react-app-revamp/app/api/contest/jklabs-split-destination-address/route.ts
  packages/react-app-revamp/app/api/contest/requirements-data/route.ts
  packages/react-app-revamp/app/api/contests/featured/route.ts
  packages/react-app-revamp/app/api/contests/live/route.ts
  packages/react-app-revamp/app/api/contests/participant-data/route.ts
  packages/react-app-revamp/app/api/contests/past/route.ts
  packages/react-app-revamp/app/api/contests/search/route.ts
  packages/react-app-revamp/app/api/contests/upcoming/route.ts
  packages/react-app-revamp/app/api/extensions/route.ts
  packages/react-app-revamp/app/api/monetization/charge-details/route.ts
  packages/react-app-revamp/app/api/rewards/token-addresses/route.ts
  packages/react-app-revamp/app/api/subscribe/is-subscribed/route.ts
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-submit/route.ts
  packages/react-app-revamp/app/api/user/allowed-to-vote/route.ts
  packages/react-app-revamp/app/api/user/comments/route.ts
  packages/react-app-revamp/app/api/user/contests/route.ts
  packages/react-app-revamp/app/api/user/submissions/route.ts
Labels: patch

#2603 chore: add no-store on each fetch fn
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/extensions/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/lib/rewards/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/vip/index.ts
Labels: chore

#2604 patch PR 9 of week ending 10/8/24
  packages/react-app-revamp/app/api/token/route.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/extensions/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/lib/rewards/index.ts
  packages/react-app-revamp/lib/user/index.tsx
  packages/react-app-revamp/lib/vip/index.ts
Labels: patch

#2613 chore: rm unused Dockerfile and .devcontainer
  .devcontainer/devcontainer.json
  Dockerfile
Labels: chore

#2576 chain: add shape
  packages/react-app-revamp/config/wagmi/custom-chains/shape.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/shape.svg
Labels: chain

#2619 wording: update language from earnings to charges
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/DeploymentStatus/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
Labels: wording

#2622 chore: token holders processing refactor
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/tokenHoldersProcessing.ts
Labels: chore

#2607 chore: remove next/image from codebase
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/ChainDropdown/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/UI/BurgerMenu/index.tsx
  packages/react-app-revamp/components/UI/ConnectButton/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/Loader/index.tsx
  packages/react-app-revamp/components/UI/MultiStepToast/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Success/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Warning/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/components/TokenWidgets/components/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/Countdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/Duplicates/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Submission/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/FileUpload/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Layout/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/components/List/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/next.config.js
Labels: chore

#2630 chain: rename MATIC to POL
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
Labels: chain

#2632 chore: bump featured to 8
  packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/lib/contests/constants/index.ts
Labels: chore

#2627 bugfix: get alchemy base url in user tokens hook
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
Labels: bugfix

#2637 bugfix: enable toast interaction when modal is open
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/portal.tsx
Labels: bugfix

#2641 bugfix: update userVotes calculation to account for gas costs separately
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: bugfix

#2645 chore: update grid count for featured contests cards
  packages/react-app-revamp/styles/globals.css
Labels: chore

#2644 patch PR 1 of week ending 10/15/24
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/portal.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/UI/Avatar/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/contests/constants/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch

#2659 bugfix: rm contest status check in user qualifications
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bugfix

#2658 chore: remove summary from codebase
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Summary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: chore

#2666 chain: update boba rpc
  packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
Labels: chain

#2667 chain: add unichainTestnet
  packages/react-app-revamp/config/wagmi/custom-chains/unichainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/unichain.png
Labels: chain

#2663 patch PR 2 of week ending 10/15/24
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Summary/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSummary/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/karaoke-challenge/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/boba.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unichainTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/unichain.png
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
  yarn.lock
Labels: patch

#2675 bugfix: add contract simulation and enhance insufficient funds error detection
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/utils/error.ts
Labels: bugfix

#2676 chore: enhance didUserReject function to catch more user rejection scenarios
  packages/react-app-revamp/utils/error.ts
Labels: chore

#2678 feat: add default value for entry and vote
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/supabase_schemas/chain_params.sql
Labels: feat

#2681 chain: switch gnosis rpc provider
  packages/react-app-revamp/config/wagmi/custom-chains/gnosis.ts
Labels: chain

#2685 chore: rm turbo
  package.json
  yarn.lock
Labels: chore

#2688 chore: lower max submissions to 1k
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: chore

#2696 patch PR 3 of week ending 10/15/24
  package.json
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/gnosis.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/supabase_schemas/chain_params.sql
  packages/react-app-revamp/utils/error.ts
  yarn.lock
Labels: patch

#2698 feat: track has been featured
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: feat

#2697 bugfix: prevent rate-limiting
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
Labels: bugfix

#2699 patch PR 4 of week ending 10/15/24
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
  packages/react-app-revamp/config/wagmi/custom-chains/base.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonZk.ts
  packages/react-app-revamp/supabase_schemas/contests_v3.sql
Labels: patch

#2701 chore: set default min supabase
  packages/react-app-revamp/supabase_schemas/chain_params.sql
Labels: chore

#2704 chore: read contest title from chain across site
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/user/index.tsx
Labels: chore

#2705 feat: show number of voters on an entry
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
Labels: feat

#2707 bugfix: early return for zero balance in checkAnyoneCanVoteUserQualification fn
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: bugfix

#2716 chore: move to public arb rpc
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
Labels: chore

#2723 chore: revert arb rpc
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
Labels: chore

#2724 patch PR 2 of week ending 10/22/24
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOne.ts
Labels: patch

#2757 chain: update camp testnet rpc
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
Labels: chain

#2759 bugfix: fix alchemy url for nft holders
  packages/react-app-revamp/lib/permissioning/index.ts
Labels: bugfix

#2773 merge sprint ending 10/22/24
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2778 chore: bump gas limit buffer
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: chore

#2786 chain: add morph
  packages/react-app-revamp/config/wagmi/custom-chains/morph.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#2792 bugfix: move sort enabled check out of monetization check
  packages/react-app-revamp/hooks/useContest/index.ts
Labels: bugfix

#2809 bugfix: catch correctly deleted entries
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/lib/proposal/index.ts
Labels: bugfix

#2810 patch PR 3 of week ending 10/29/24
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/lib/proposal/index.ts
Labels: patch

#2813 chain: update camp v2
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
Labels: chain

#2815 patch PR 4 of week ending 10/29/24
  packages/react-app-revamp/config/wagmi/custom-chains/campTestnet.ts
Labels: patch

#2818 enhancement: update voting info in params tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
Labels: enhancement

#2817 chore: add faq to footer
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: chore

#2816 chore: auto enable monetization on all testnet chains
  packages/react-app-revamp/lib/monetization/index.ts
Labels: chore

#2821 merge sprint ending 10/29/24
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#2822 chore: remove medium image compression for now
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
Labels: chore

#2824 patch PR 1 of week ending 11/5/24
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
Labels: patch

#2834 bugfix: do not fetch jklabs address from chains_params if chain is testnet
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bugfix

#2833 enhancement: apply entry preview enhancements
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/UI/ImageUpload/utils.ts
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/Editor/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Delete/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: enhancement

#2836 chore: fix typo for csvs file name in params tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
Labels: chore

#2837 patch PR 2 of week ending 11/5/24
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/UI/ImageUpload/utils.ts
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Submitters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/Editor/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Delete/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#2843 chain: update hedera rpc
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
Labels: chain

#2842 bugfix: add overflow hidden to entry container in leaderboards
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
Labels: bugfix

#2841 bugfix: add default metadata fields in constructor
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/lib/proposal/index.ts
Labels: bugfix

#2846 patch PR 3 of week ending 11/5/24
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/hedera.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch
