Repository jk-labs-inc/jokerace, pull requests merged in 2024-03, with the labels that each got.

#1401 bugfix: fix parsing of submission cost
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#1402 patch PR 5 of week ending 3/5/24
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: patch

#1404 chain: add blast and dymension
  packages/react-app-revamp/config/wagmi/custom-chains/blast.ts
  packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
  packages/react-app-revamp/config/wagmi/index.ts
Labels: chain

#1405 chore: clean up build
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1409 chore: add dymension and blast logos
  packages/react-app-revamp/config/wagmi/custom-chains/blast.ts
  packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
  packages/react-app-revamp/public/blast.svg
  packages/react-app-revamp/public/dymension.png
Labels: chore

#1406 patch PR 6 of week ending 3/5/24
  packages/react-app-revamp/config/wagmi/custom-chains/blast.ts
  packages/react-app-revamp/config/wagmi/custom-chains/blastTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/blast.svg
  packages/react-app-revamp/public/dymension.png
  yarn.lock
Labels: patch

#1411 chore: update jokerace logo
  packages/react-app-revamp/public/jokerace.jpg
Labels: chore

#1412 patch PR 7 of week ending 3/5/24
  packages/react-app-revamp/public/jokerace.jpg
Labels: patch

#1415 chore: remove decimals from contest
  packages/react-app-revamp/components/UI/Slider/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerContest/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/SubmissionsPerPlayer/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/components/CSVEditor/TableRow/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/workers/parseVotingCsv.ts
  packages/react-app-revamp/workers/tokenHoldersProcessing.ts
Labels: chore

#1421 chore: get RewardsModule bytecode up to speed
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.4.26.cleanUpConstructors.sol/RewardsModule.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/modules/RewardsModule.sol/RewardsModule.json
Labels: chore

#1425 chain: add astar, merlin, and zkfair main and testnets
  packages/react-app-revamp/config/wagmi/custom-chains/astarZkevm.ts
  packages/react-app-revamp/config/wagmi/custom-chains/astarZkevmTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/merlin.ts
  packages/react-app-revamp/config/wagmi/custom-chains/merlinTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zkFair.ts
  packages/react-app-revamp/config/wagmi/custom-chains/zkFairTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/astar.png
  packages/react-app-revamp/public/merlin.png
  packages/react-app-revamp/public/zkFair.png
Labels: chain

#1428 chain: rm dymension and transition polygon testnet
  packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/dymension.png
Labels: chain

#1429 patch PR 2 of week ending 3/12/24
  packages/react-app-revamp/config/wagmi/custom-chains/dymension.ts
  packages/react-app-revamp/config/wagmi/custom-chains/polygonTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/dymension.png
Labels: patch

#1430 chain: add inEvm main and testnets
  packages/react-app-revamp/config/wagmi/custom-chains/inEvm.ts
  packages/react-app-revamp/config/wagmi/custom-chains/inEvmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/inEvm.png
Labels: chain

#1431 patch PR 3 of week ending 3/12/24
  packages/react-app-revamp/config/wagmi/custom-chains/inEvm.ts
  packages/react-app-revamp/config/wagmi/custom-chains/inEvmTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/inEvm.png
Labels: patch

#1432 chore: speed up builds with hard yarn.lock reset
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1435 bugfix: set sorting to 0 if downvoting enabled
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bugfix

#1436 patch PR 4 of week ending 3/12/24
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#1438 feat: add contact field in description page
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestPrompt/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: feat

#1437 chore: update viem
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1444 bugfix: add check for contact details in deploy contest fn
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bugfix

#1448 patch PR 1 of week ending 3/19/24
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/hooks/useTokenList/index.ts
Labels: patch

#1456 patch 2 of week ending 3/19/24
  packages/react-app-revamp/components/ChargeLayout/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
Labels: patch

#1450 feat: anyone can vote frontend
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Stepper/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Allowlists/components/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingAllowlist/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/validation.ts
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalContentAction/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useAccountChange/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContest/v3v4/contracts.ts
  packages/react-app-revamp/hooks/useContestInfo/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/store.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/components/Error/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/workers/indexContestParticipants.ts
Labels: feat

#1458 enhancement: eliminate joker
  packages/react-app-revamp/components/UI/Loader/index.tsx
  packages/react-app-revamp/components/UI/Loader/styles.ts
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/public/favicon.png
Labels: enhancement

#1459 feat: embed tweet in proposal preview
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/helpers/isContentTweet.ts
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/styles/globals.css
Labels: feat

#1460 chore: hydrate cookie for wagmi ssr
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/providers/index.tsx
Labels: chore

#1464 bugfix: revert "chore: hydrate cookie for wagmi ssr (#1460)"
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/providers/index.tsx
Labels: bugfix

#1463 patch PR 1 of week ending 3/26/24
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/providers/index.tsx
Labels: patch

#1465 chore: typo fix
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
Labels: chore

#1468 chore: make test funcs view
  packages/forge/test/Contest.t.sol
Labels: chore

#1470 chore: hydrate cookies for ssr
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/providers/index.tsx
  yarn.lock
Labels: chore

#1471 patch PR 3 of week ending 3/26/24
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
  packages/react-app-revamp/providers/index.tsx
  yarn.lock
Labels: patch

#1472 bugfix: pass chainId from getServerSideProps on submission page
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: bugfix

#1473 patch PR 4 of week ending 3/26/24
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
Labels: patch

#1474 chore: retrieve add votes text in proposal
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: chore

#1478 chore: upgrade viem and tanstack react query
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#1480 patch PR 6 of week ending 3/26/24
  packages/react-app-revamp/config/wagmi/custom-chains/neon.ts
  packages/react-app-revamp/config/wagmi/custom-chains/neonDevnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/neon.png
Labels: patch

#1482 chore: use initialProps in app rather than server side prop on each page
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
Labels: chore

#1485 patch PR 7 of week ending 3/26/24
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/pages/_app.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/index.tsx
  packages/react-app-revamp/pages/contest/[chain]/[address]/submission/[submission]/index.tsx
  packages/react-app-revamp/pages/contest/new/index.tsx
  packages/react-app-revamp/pages/contests/index.tsx
  packages/react-app-revamp/pages/contests/live/index.tsx
  packages/react-app-revamp/pages/contests/past/index.tsx
  packages/react-app-revamp/pages/contests/upcoming/index.tsx
  packages/react-app-revamp/pages/index.tsx
  packages/react-app-revamp/pages/user/[address]/comments/index.tsx
  packages/react-app-revamp/pages/user/[address]/index.tsx
  packages/react-app-revamp/pages/user/[address]/submissions/index.tsx
  packages/react-app-revamp/pages/user/[address]/votes/index.tsx
Labels: patch

#1487 chore: rm mirror and token links
  packages/react-app-revamp/components/Header/CreateFlowHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/pages/index.tsx
Labels: chore

#1484 chore: remove BigNumber across the codebase
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/components/TotalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/components/TotalVotesCast/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContestEvents/index.ts
  packages/react-app-revamp/hooks/useFetchUserVotesOnProposal/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/store.tsx
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/index.ts
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/store.tsx
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
Labels: chore

#1496 wording: update anyone can vote
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
Labels: wording

#1498 enhancement: apply monetization page text change
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
Labels: enhancement

#1497 bugfix: fix funding pool for erc20 tokens on base
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/hooks/useFundRewards/index.ts
Labels: bugfix

#1491 chore: deprecate goerli
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lineaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/tokens.ts
Labels: chore

#1499 patch PR 9 of week ending 3/26/24
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnsupportedChain/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Fund/index.tsx
  packages/react-app-revamp/components/_pages/RewardsTable/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/arbitrumOneTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/goerli.ts
  packages/react-app-revamp/config/wagmi/custom-chains/lineaTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/optimismTestnet.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scrollTestnet.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/helpers/tokens.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useFundRewards/index.ts
Labels: patch

#1500 feat: add erc1155 permission in create flow
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: feat

#1501 enhancement: use generic user icon for profile
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/public/contest/user.svg
Labels: enhancement

#1502 merge sprint ending 3/26/24
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/public/contest/user.svg
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: sprint end

#1505 chore: remove logging
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
Labels: chore

#1504 patch PR 1 of week ending 4/2/24
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
Labels: patch

#1506 chore: implement string input to erc1155 tokenId field
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: chore

#1507 patch PR 2 of week ending 4/2/24
  packages/react-app-revamp/components/_pages/Create/components/NumberInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestSubmission/components/SubmissionRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/components/NFT/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/DialogCheckBalanceRewardsModule/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useSearchNfts/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
  packages/react-app-revamp/workers/nftOwnersProcessing.ts
Labels: patch

#1508 bugfix: add max-width for react-tweet on mobile
  packages/react-app-revamp/styles/globals.css
Labels: bugfix

#1509 patch PR 3 of week ending 4/2/24
  packages/react-app-revamp/styles/globals.css
Labels: patch

#1510 chain: add degen
  packages/react-app-revamp/config/wagmi/custom-chains/degen.ts
  packages/react-app-revamp/config/wagmi/custom-chains/degenChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/degen.png
Labels: chain

#1511 patch PR 4 of week ending 4/2/24
  packages/react-app-revamp/config/wagmi/custom-chains/degen.ts
  packages/react-app-revamp/config/wagmi/custom-chains/degenChain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/public/degen.png
Labels: patch
