Repository jk-labs-inc/jokerace, pull requests merged in 2025-01, with the labels that each got.

#3206 chore: add substack to footer
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: chore

#3208 patch PR 1 of week ending 1/14/25
  .github/workflows/forge_tests.yml
  packages/forge/foundry.toml
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3212 chore: add dune supported chain names
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
Labels: chore

#3213 enhancement: remove gap between entry navigation and menu bar on mobile
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#3215 merge sprint ending 1/14/25
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/utils/index.ts
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: sprint end

#3224 enhancement: contest page real estate redesign
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/hooks/useLineCount/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#3225 chain: add lukso
  packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#3226 enhancement: attach enter contest btn to the bottom on mobile
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
Labels: enhancement

#3227 patch PR 1 of week ending 1/21/25
  packages/react-app-revamp/components/Share/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useLineCount/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3229 bugfix: cors checksum aws update issue
  packages/react-app-revamp/config/s3/index.ts
Labels: bugfix

#3232 patch PR 2 of week ending 1/21/25
  packages/react-app-revamp/config/s3/index.ts
Labels: patch

#3237 chore: add s3 response checksum validation
  packages/react-app-revamp/config/s3/index.ts
Labels: chore

#3238 patch PR 3 of week ending 1/21/25
  packages/react-app-revamp/config/s3/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3245 enhancement: fix dropdown chevron positioning in tag input
  packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
Labels: enhancement

#3249 bugfix: prevent duplicate analytics entries by sequential executions
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#3233 chore: rm pinned dep
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3250 merge sprint ending 1/21/25
  packages/react-app-revamp/components/_pages/Create/components/TagDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TextInput/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTitle/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#3267 enhancement: improve and streamline entry page
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/Tabs/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/EntryNavigation/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/VoteCountdown/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: enhancement

#3274 patch PR 1 of week ending 2/4/25
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/UI/Tabs/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Tabs/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/EntryNavigation/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/VoteCountdown/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogWithdrawFundsFromRewardsModule/ButtonWithdraw.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch
