Repository jk-labs-inc/jokerace, pull requests merged in 2025-09, with the labels that each got.

#4460 patch PR 3 of week ending 9/2/25
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/CancelRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/WithdrawRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/RewardsCanceled/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/RewardsCanceled/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/CancelContest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ProposalStatistics/components/Panel/components/VotingOpenOrClosed/components/TotalVotesCast/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/hooks/useCancelRewards/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useTotalVotesCastOnContest/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4455 chore: deprecate ethers
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
  packages/react-app-revamp/config/wagmi/transports.ts
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/getBlock.ts
  packages/react-app-revamp/helpers/getChainFromId.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/getVoterRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/viem.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useDeployContest/helpers/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useVoterRewardsStatistics/index.ts
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/workers/generateProof.ts
  yarn.lock
Labels: chore

#4463 merge sprint ending 9/2/25
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
  packages/react-app-revamp/config/wagmi/transports.ts
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/getBlock.ts
  packages/react-app-revamp/helpers/getChainFromId.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/helpers/getRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/getVoterRewardsModuleContractVersion.ts
  packages/react-app-revamp/helpers/viem.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useDeployContest/helpers/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useVoterRewardsStatistics/index.ts
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/workers/generateProof.ts
  yarn.lock
Labels: sprint end

#4472 chore: rm vscode folder
  .vscode/settings.json
Labels: chore

#4488 test: add official rewards module registration test
  packages/forge/test/VoterRewardsModule.t.sol
Labels: test

#4516 patch PR 4 of week ending 9/9/25
  .github/workflows/nextjs_build.yml
  .github/workflows/nextjs_docker.yml
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/CSV/Voters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/components/CostToVote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/components/Curves/components/ExponentialPricingOption/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
  packages/react-app-revamp/database_schemas/supabase/chain_params.sql
  packages/react-app-revamp/database_schemas/supabase/user_permissions.sql
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useDeployContest/helpers/constructorArgs.ts
  packages/react-app-revamp/hooks/useDeployContest/slices/contestMonetizationSlice.ts
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/hooks/useVoters/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/lib/monetization/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/workers/fetchDataFromBucket.ts
  packages/react-app-revamp/workers/generateProof.ts
  yarn.lock
Labels: patch

#4518 chore: rename sorting tests
  packages/forge/test/VoterRewardsModule.t.sol
Labels: test

#4541 chore: rm pre-v4 bytecode
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.1.pre-prompt.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.10.betterRewardsNotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.2.prompt.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.3.allProposalTotalVotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.4.proposalVotesDownvotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.5.submissionTokenGating.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.6.rewards.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.7.noTiesFound.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.8.numberedVersioning.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.2.9.gateSubmissionsOpen.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.1.merkleVotes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.10.cantVoteOnDeletedProps.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.11.auditMinorFixes.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.12.auditInfoAndOptimizations.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.13.cleanUpContractDocs.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.14.trackProposalAuthors.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.15.trackVoters.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.16.makeVarsPublic.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.17.letJkLabsCancel.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.18.addJokeraceCreatedEvent.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.2.totalVotesCast.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.3.setCompilerTo8Dot19.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.4.addIsDeleted.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.5.deletedDontHitLimit.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.6.bringBackDeletedIds.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.7.makeArrayOfDeletedIds.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.8.makeDeletedIdAccessor.sol/Contest.json
  packages/react-app-revamp/contracts/bytecodeAndAbi/Contest.3.9.privateDeletedIds.sol/Contest.json
Labels: chore

#4571 chore: roll back viem update to 2.37.6
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#4570 patch PR 5 of week ending 9/16/25
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4577 bugfix: wagmi lockfile issue
  packages/react-app-revamp/package.json
  yarn.lock
Labels: bugfix

#4590 patch PR 1 of week ending 9/23/25
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/email/types.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4616 patch PR 2 of week ending 9/23/25
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4656 merge sprint ending 9/30/25
  packages/react-app-revamp/app/globals.css
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end
