Repository jk-labs-inc/jokerace, pull requests merged in 2025-03, with the labels that each got.

#3397 bugfix: fix entry sorting after submitting
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix

#3414 bugfix: fix full description btn overflow
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
Labels: bugfix

#3409 bugfix: enrich tweet not found component
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-not-found.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
Labels: bugfix

#3398 enhancement: implement create flow polishes
  packages/react-app-revamp/components/_pages/Create/components/GradientTitle/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RadioButtonsGroup/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestEntries/components/AdditionalDescription/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestEntries/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/UnconnectedAccount/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/config.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRadioGroup/index.tsx
Labels: enhancement

#3407 chore: deprecate visibility feature
  packages/react-app-revamp/app/user/[address]/contests.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Customization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/components/ContestVisibility/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestParams/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/index.tsx
  packages/react-app-revamp/database_schemas/supabase/contests_v3.sql
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/lib/creator/index.ts
Labels: chore

#3428 enhancement: update rewards info color
  packages/react-app-revamp/components/UI/GradientText/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
Labels: enhancement

#3427 enhancement: update get more token color
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: enhancement

#3430 chore: add missing children to gradient text in templates
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
Labels: chore

#3433 chore: add new env vars to README
  README.md
  packages/react-app-revamp/README.md
Labels: chore

#3440 enhancement: template polishes
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Layout/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/live-contest/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/test-contest/index.tsx
  packages/react-app-revamp/helpers/textUtils.ts
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
Labels: enhancement

#3441 bugfix: fix entry alignment on mobile
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
Labels: bugfix

#3458 chore: update tag format in contest cards
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
Labels: chore

#3434 patch PR 1 of week ending 3/11/25
  README.md
  packages/react-app-revamp/README.md
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/CSVErrorModal/components/InvalidEntries/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Layout/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Preview/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/live-contest/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/test-contest/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/helpers/textUtils.ts
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3444 feat: implement rewards flow v4
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/Table/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
Labels: feat

#3461 bugfix: enable next button after wallet is connected in monetization step
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
Labels: bugfix

#3468 enhancement: add light mode to tweet component
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-tweet.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx
Labels: enhancement

#3469 merge sprint ending 3/11/25
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/Table/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useNextStep.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-tweet.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#3482 bugfix: fix scroll threshold for entries
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/skeleton.tsx
Labels: bugfix

#3483 patch PR 1 of week ending 3/18/25
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/skeleton.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3467 chore: be resilient about r2 failures
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/components/EditContestName/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RadioButtonsGroup/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/UploadImage/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageAndTitleLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/ImageLayout/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/lib/buckets/index.tsx
Labels: chore

#3491 bugfix: fix vote charge settings
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
Labels: bugfix

#3490 feat: add version control and remove downvoting frontend
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useFetchUserVotesOnProposal/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
Labels: feat

#3497 enhancement: show 5 ranks in rewards flow
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
Labels: enhancement

#3511 enhancement: implement higher contrast borders for entries
  packages/react-app-revamp/tailwind.config.js
Labels: enhancement

#3496 chore: update split across the codebase and site
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/EntryBased/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/VotingBased/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
Labels: chore

#3528 feat: always require wallet address for email updates
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: feat

#3524 chain: add berachain
  packages/react-app-revamp/config/wagmi/custom-chains/berachain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#3529 wording: remove qualified wording on params tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
Labels: wording

#3527 enhancement: add warning for max votes
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/TotalCharge/index.tsx
  packages/react-app-revamp/components/UI/ButtonV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogMaxVotesAlert/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/helpers/nativeToken.ts
  packages/react-app-revamp/helpers/totalCharge.ts
Labels: enhancement

#3519 chore: implement referer in ethers and server config
  packages/react-app-revamp/app/contest/[chain]/[address]/submission/[submission]/page.tsx
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/helpers/ethers.ts
Labels: chore

#3536 chore: resurface privacy policy
  PrivacyPolicy.md
Labels: chore

#3534 wording: add recommended to entry open time
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
Labels: wording

#3533 enhancement: add dynamic text for summary in create flow
  packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
Labels: enhancement

#3537 merge sprint ending 3/25/25
  PrivacyPolicy.md
  packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#3547 chore: reduce image file upload size
  packages/react-app-revamp/components/UI/ImageUpload/index.tsx
Labels: chore

#3548 chore: add fonts to folder
  packages/react-app-revamp/app/_fonts/Lato-Black.woff2
  packages/react-app-revamp/app/_fonts/Lato-Bold.woff2
  packages/react-app-revamp/app/_fonts/Lato-Regular.woff2
  packages/react-app-revamp/app/_fonts/Sabo-Filled.otf
  packages/react-app-revamp/app/layout.tsx
Labels: chore

#3549 chore: rm unused imports
  packages/react-app-revamp/app/user/[address]/submissions/submissions.tsx
  packages/react-app-revamp/components/ChargeLayout/components/CommisionDetails/index.tsx
  packages/react-app-revamp/components/Comments/components/Form/components/Input/components/SubmitButton/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/index.tsx
  packages/react-app-revamp/components/UI/Collapsible/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Contest/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Navigation/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/components/EditContestPrompt/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Timeline/index.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useSubmissionMerkle.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRadioGroup/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/components/_pages/DialogAddFundsToRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/TweetLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/custom-not-found.tsx
  packages/react-app-revamp/components/_pages/Rewards/components/Withdraw/index.tsx
  packages/react-app-revamp/config/rainbowkit/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: chore

#3541 enhancement: slow navigation between pages
  packages/react-app-revamp/app/contest/new/loading.tsx
  packages/react-app-revamp/app/contests/search.tsx
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/UI/Link/index.tsx
  packages/react-app-revamp/components/UI/Menu/Link/index.tsx
  packages/react-app-revamp/components/UI/MobileWalletPortal/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/SuccessLayout/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/components/_pages/ListContests/Contest/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Classic/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/CommentsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/SubmissionsList/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/components/List/index.tsx
  packages/react-app-revamp/components/_pages/User/components/VotingList/index.tsx
  packages/react-app-revamp/layouts/LayoutContests/index.tsx
  packages/react-app-revamp/layouts/LayoutUser/index.tsx
  packages/react-app-revamp/layouts/LayoutViewContest/components/Error/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: enhancement

#3552 chore: fix vote calculation precision with Math.floor
  packages/react-app-revamp/hooks/useUser/index.ts
Labels: chore

#3559 bugfix: fix undefined BigInt conversion in entry votes
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
Labels: bugfix

#3560 enhancement: use light class selector for tweets
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx
Labels: enhancement
