Repository jk-labs-inc/jokerace, pull requests merged in 2025-04, with the labels that each got.

#3561 chore: add scroll false when routing with router
  packages/react-app-revamp/components/_pages/Submission/index.tsx
Labels: chore

#3573 patch PR 1 of week ending 4/8/25
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/utils/markdown.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposal/utils.ts
  packages/react-app-revamp/hooks/useUser/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3575 bugfix: fix bsod on templates if wallet is not connected
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
Labels: bugfix

#3567 wording: update split charges text
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
Labels: wording

#3582 bugfix: fix collapsed description container height to prevent extra scrolling
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
Labels: bugfix

#3583 patch PR 2 of week ending 4/8/25
  packages/react-app-revamp/components/Comments/components/Comment/index.tsx
  packages/react-app-revamp/components/Comments/components/List/index.tsx
  packages/react-app-revamp/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/Proposal/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Modal/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/Prompt/components/Page/components/Layout/V3/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/DialogMaxVotesAlert/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/components/VoterRow/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/components/Comments/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/components/VoteFooter/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/components/VotersList/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3598 chore: add try/catch for signer during contest deployment
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#3600 chain: add unichain
  packages/react-app-revamp/config/wagmi/custom-chains/unichain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#3601 chore: add privacy policy to footer
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
Labels: chore

#3602 chain: add swell
  packages/react-app-revamp/config/wagmi/custom-chains/swell.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/swell.png
Labels: chain

#3603 merge sprint ending 4/8/25
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/ContestName/index.tsx
  packages/react-app-revamp/config/links/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/swell.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unichain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/layouts/LayoutBase/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/swell.png
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: sprint end

#3624 feat: add ability for creator/entrant to delete entry on frontend
  packages/react-app-revamp/components/UI/DialogModalV3/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/skeleton.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/Submission/components/Buttons/Delete/index.tsx
  packages/react-app-revamp/components/_pages/Submission/components/Modals/Delete/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
Labels: feat

#3630 wording: update split toggle on rewards page
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
Labels: wording

#3638 bugfix: rm hardcoded votes on entry page on desktop
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
Labels: bugfix

#3639 patch PR 2 of week ending 4/14/25
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3641 patch PR 3 of week ending 4/14/25
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
Labels: patch

#3629 enhancement: replace email signups from toggle to optional
  packages/react-app-revamp/components/_pages/Create/components/GradientTitle/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/AdditionalDescriptionLayout/index.tsx
Labels: enhancement

#3643 enhancement: display error on featured contest card
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
Labels: enhancement

#3642 chore: implement masonic virtualization
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3645 bugfix: fix close button style on entry page on desktop
  packages/react-app-revamp/components/_pages/DialogModalProposal/components/Header/index.tsx
Labels: bugfix

#3646 chore: prefetch close entry action on entry page
  packages/react-app-revamp/components/_pages/Submission/index.tsx
Labels: chore

#3648 enhancement: put additional text in white bold and rm italic
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/MetadataFields/components/MetadataField/index.tsx
  packages/react-app-revamp/helpers/metadata.ts
Labels: enhancement

#3653 chore: rm view transition lib
  packages/react-app-revamp/app/contests/search.tsx
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/UI/Link/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3654 patch PR 2 of week ending 4/22/25
  packages/react-app-revamp/app/contests/search.tsx
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/components/Header/CreateFlowHeader/DesktopLayout/index.tsx
  packages/react-app-revamp/components/Sort/index.tsx
  packages/react-app-revamp/components/UI/Link/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/components/_pages/Submission/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3655 wording: guide new users to para
  packages/react-app-revamp/config/wagmi/index.ts
Labels: wording

#3656 patch PR 3 of week ending 4/22/25
  packages/react-app-revamp/config/wagmi/index.ts
Labels: patch

#3652 enhancement: add filled mobile nav buttons
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/UI/Icons/index.tsx
Labels: enhancement

#3673 bugfix: fix arbitrum onramp
  packages/react-app-revamp/components/Onramp/providers/coinbase/utils.ts
Labels: bugfix

#3676 merge sprint ending 4/22/25
  packages/react-app-revamp/components/Header/LandingHeader/index.tsx
  packages/react-app-revamp/components/Header/MainHeader/MobileLayout/index.tsx
  packages/react-app-revamp/components/Onramp/providers/coinbase/utils.ts
  packages/react-app-revamp/components/UI/Icons/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/lukso.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#3694 patch PR 1 of week ending 4/29/25
  packages/react-app-revamp/components/_pages/Create/components/ConnectPrompt/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/index.tsx
  packages/react-app-revamp/helpers/getNativeTokenInfo.ts
  packages/react-app-revamp/package.json
  renovate.json
  yarn.lock
Labels: patch

#3702 chore: rm lens protocol client
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3698 enhancement: add funds polishes
  packages/react-app-revamp/components/ChargeLayout/components/Submission/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/Onramp/components/Card/index.tsx
  packages/react-app-revamp/components/Onramp/providers/coinbase/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/VotingQualifierMessage/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Submit/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
Labels: enhancement

#3672 chore: disable coinbase wallet for creating a contest
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Info/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/utils.ts
Labels: chore

#3716 chore: add berachain to dune extension
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
Labels: chore

#3719 chore: rm eslint build error
  packages/react-app-revamp/.eslintrc.json
Labels: chore

#3730 chore: rm valibot
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3732 chore: rm server component error message
  packages/react-app-revamp/app/not-found.tsx
Labels: chore

#3734 patch PR 3 of week ending 4/29/25
  packages/react-app-revamp/.eslintrc.json
  packages/react-app-revamp/app/not-found.tsx
  packages/react-app-revamp/components/_pages/Contest/Extensions/components/List/Dune/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3682 chore: allow major update PRs to be made without approval
  renovate.json
Labels: chore

#3729 enhancement: strokes on buttons and cards
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Vote/Primary/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Vote/Secondary/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/public/contest/upvote-2.svg
  packages/react-app-revamp/public/contest/upvote-3.svg
  packages/react-app-revamp/public/contest/upvote-mobile.svg
  packages/react-app-revamp/tailwind.config.js
  yarn.lock
Labels: enhancement
