Repository jk-labs-inc/jokerace, pull requests merged in 2025-05, with the labels that each got.

#3763 chore: fix JsonRpcProvider retry error
  packages/react-app-revamp/helpers/ethers.ts
Labels: chore

#3753 patch PR 1 of week ending 5/6/25
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/portal.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/utils/csv.ts
  packages/react-app-revamp/components/_pages/DialogAddFundsToRewardsModule/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Vote/Primary/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/Buttons/Vote/Secondary/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/components/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/index.tsx
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/helpers/getBlock.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployRewards/index.ts
  packages/react-app-revamp/hooks/useEditContestTitleAndImage/index.tsx
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/lib/merkletree/generateMerkleTree.ts
  packages/react-app-revamp/lib/participants/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/contest/upvote-2.svg
  packages/react-app-revamp/public/contest/upvote-3.svg
  packages/react-app-revamp/public/contest/upvote-mobile.svg
  packages/react-app-revamp/tailwind.config.js
  packages/react-app-revamp/workers/generateProof.ts
  renovate.json
  yarn.lock
Labels: patch

#3758 chore: rm pinned deps
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3748 chore: always show add funds optional link if user has funds when voting
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
Labels: chore

#3736 test: clean up descriptions and add old val test
  packages/forge/test/RewardsModule.t.sol
Labels: test

#3767 patch PR 2 of week ending 5/6/25
  packages/forge/test/RewardsModule.t.sol
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/helpers/textUtils.ts
  packages/react-app-revamp/hooks/useCastVotes/store.tsx
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContractFactory/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/store.tsx
  packages/react-app-revamp/hooks/useProposal/store.tsx
  packages/react-app-revamp/hooks/useRewards/store.tsx
  packages/react-app-revamp/hooks/useUser/store.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3771 chore: bring back react native dep
  renovate.json
Labels: chore

#3775 chore: update README and remove extra
  README.md
  packages/react-app-revamp/README.md
Labels: chore

#3790 chain: add manta
  packages/react-app-revamp/config/wagmi/custom-chains/manta.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/manta.svg
Labels: chain

#3793 bugfix: prevent user from submitting invalid tweet entry
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/components/TweetLayout/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/components/EntryPreviewLayout/index.tsx
Labels: bugfix

#3764 fix(deps): update nextjs monorepo to v15
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/user/[address]/comments/page.tsx
  packages/react-app-revamp/app/user/[address]/page.tsx
  packages/react-app-revamp/app/user/[address]/submissions/page.tsx
  packages/react-app-revamp/app/user/[address]/votes/page.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  yarn.lock
Labels: renovate

#3795 patch PR 4 of week ending 5/6/25
  packages/react-app-revamp/app/api/tweet/[id]/route.ts
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/app/user/[address]/comments/page.tsx
  packages/react-app-revamp/app/user/[address]/page.tsx
  packages/react-app-revamp/app/user/[address]/submissions/page.tsx
  packages/react-app-revamp/app/user/[address]/votes/page.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/index.tsx
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3796 patch PR 5 of week ending 5/5/25
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/hooks/useTotalVotes/index.ts
  packages/react-app-revamp/lib/contests/constants/index.ts
  packages/react-app-revamp/lib/contests/contracts.ts
  packages/react-app-revamp/lib/contests/index.ts
  packages/react-app-revamp/lib/contests/types.ts
  packages/react-app-revamp/lib/contests/utils/streamItems.ts
  packages/react-app-revamp/lib/user/index.tsx
Labels: patch

#3766 bugfix: fix referer implementation
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/config/wagmi/transports.ts
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
Labels: bugfix

#3807 patch PR 1 of week ending 5/13/25
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/components/Subscribe/index.tsx
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Tweet/components/CustomTweet/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/config/wagmi/transports.ts
  packages/react-app-revamp/helpers/ethers.ts
  packages/react-app-revamp/helpers/getContestContractVersion.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3834 patch PR 2 of week ending 5/13/25
  packages/react-app-revamp/next-env.d.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3857 patch PR 1 of week ending 5/20/25
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3859 chain: add zksync era
  packages/react-app-revamp/config/wagmi/custom-chains/zksyncEra.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/zksyncEra.png
Labels: chain

#3864 merge sprint ending 5/20/25
  packages/react-app-revamp/config/wagmi/custom-chains/zksyncEra.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/zksyncEra.png
  yarn.lock
Labels: sprint end

#3871 patch PR 1 of week ending 5/27/25
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch
