Repository jk-labs-inc/jokerace, pull requests merged in 2025-06, with the labels that each got.

#3918 bugfix: switch chain in claim rewards
  packages/react-app-revamp/hooks/useClaimRewards/index.ts
Labels: bugfix

#3931 chore: use quicknode for mantle rpc
  packages/react-app-revamp/config/wagmi/custom-chains/mantle.ts
Labels: chore

#3930 patch PR 1 of week ending 6/10/25
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/mantle.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/zksyncEra.png
  yarn.lock
Labels: patch

#3938 bugfix: use data instead of index in rewards table in rules tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Rewards/components/Table/index.tsx
Labels: bugfix

#3939 patch PR 2 of week ending 6/10/25
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Rewards/components/Table/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3962 wording: update entering and voting messages in rules tab
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
Labels: wording

#3963 bugfix: validate all calls for rewards on landing page
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/lib/contests/contracts.ts
Labels: bugfix

#3944 enhancement: add tie visuals to rewards
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Voters/Player/components/VoterClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Voters/Player/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Winners/Player/components/WinnerClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Winners/Player/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/Layout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/ClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedStatus/components/TiedStatusMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedStatus/index.tsx
  packages/react-app-revamp/hooks/useUserTiedRankings/index.ts
  packages/react-app-revamp/public/rewards/rewards-tied.png
Labels: enhancement

#3971 merge sprint ending 6/10/25
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Voters/Player/components/VoterClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Voters/Player/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Winners/Player/components/WinnerClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/Winners/Player/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/Layout/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/ClaimRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedRewards/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedStatus/components/TiedStatusMessage/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/PlayerView/TiedStatus/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/hooks/useUserTiedRankings/index.ts
  packages/react-app-revamp/lib/contests/contracts.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/rewards/rewards-tied.png
  yarn.lock
Labels: sprint end

#3976 bugfix: fix cancel tx behaviour in create flow
  packages/react-app-revamp/app/contest/[chain]/[address]/layout.tsx
  packages/react-app-revamp/app/contest/new/new.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
  packages/react-app-revamp/hooks/useContractFactory/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: bugfix

#3980 bugfix: prevent duplicate recipient selection in rewards
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Dropdown/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/CreatePool/components/Recipients/index.tsx
Labels: bugfix

#4010 feat: frontend set period limits
  packages/react-app-revamp/components/_pages/Create/components/DatePicker/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Timing/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/SubmissionPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/components/VotingPeriod/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTiming/utils.ts
Labels: feat

#4023 chore: rm geoblocking
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/components/Voting/components/NotAllowed/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/Initial/components/RewardsTypeInfo/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/hooks/useLocationPermission/index.ts
  packages/react-app-revamp/lib/geoblocking/config.ts
  packages/react-app-revamp/lib/geoblocking/locationService.ts
  packages/react-app-revamp/lib/geoblocking/types.ts
  packages/react-app-revamp/public/contest/voting-not-allowed.png
Labels: chore

#4045 chain: add sonic
  packages/react-app-revamp/config/wagmi/custom-chains/sonic.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/sonic.png
Labels: chain

#4046 patch PR 1 of week ending 7/1/25
  packages/react-app-revamp/config/wagmi/custom-chains/sonic.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/sonic.png
  renovate.json
  yarn.lock
Labels: patch

#4055 chore: disable tiptap updates pt2
  renovate.json
Labels: chore

#4068 patch PR 1 of week ending 7/1/25
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useDeployContest/store.tsx
  packages/react-app-revamp/package.json
  renovate.json
  yarn.lock
Labels: patch
