Repository jk-labs-inc/jokerace, pull requests merged in 2025-02, with the labels that each got.

#3299 enhancement: add min-height for images in entry preview
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
Labels: enhancement

#3300 patch PR 1 of week ending 2/11/25
  packages/react-app-revamp/components/_pages/ProposalContent/components/ImageWithFallback/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#3307 chore: lower concurrent calls
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useProposal/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
Labels: chore

#3306 enhancement: add testnet warning in create flow
  packages/react-app-revamp/components/UI/Deployment/Testnet/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/index.tsx
Labels: enhancement

#3305 wording: update landing page text
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
Labels: wording

#3325 enhancement: add chevron instead of bullets on landing page text
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
Labels: enhancement

#3329 chain: add soneium
  packages/react-app-revamp/config/wagmi/custom-chains/soneium.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chain

#3348 chore: rm lens
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/config/lens/index.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/next.config.js
Labels: chore

#3349 chore: rm browserlist warning
  yarn.lock
Labels: chore

#3350 chore: rm pinned dep
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#3355 chain: add story
  packages/react-app-revamp/config/wagmi/custom-chains/story.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/story.png
Labels: chain

#3340 feat: implement para embedded wallet
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/para/index.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: feat

#3357 patch PR 2 of week ending 2/18/25
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/app/layout.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/config/lens/index.ts
  packages/react-app-revamp/config/wagmi/custom-chains/story.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/para/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/next.config.js
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/story.png
  packages/react-app-revamp/styles/globals.css
  yarn.lock
Labels: patch

#3367 enhancement: add warning about voters arbing rewards pool
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddFunds/index.tsx
Labels: enhancement

#3366 chain: update celo logo
  packages/react-app-revamp/public/celo.svg
Labels: chain

#3365 bugfix: add faq link to voting contest type in create contest
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
Labels: bugfix

#3364 wording: lowercase create contest button on landing page
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
Labels: wording

#3356 feat: implement email automations
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/app/api/brevo/send/route.ts
  packages/react-app-revamp/config/brevo/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useEmailSend/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/email/index.ts
  packages/react-app-revamp/lib/email/types.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: feat

#3368 merge sprint ending 2/18/25
  .github/workflows/nextjs_build.yml
  packages/react-app-revamp/app/api/brevo/send/route.ts
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddFunds/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/config/brevo/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useEmailSend/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/lib/email/index.ts
  packages/react-app-revamp/lib/email/types.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/celo.svg
  yarn.lock
Labels: sprint end

#3372 chain: add ink
  packages/react-app-revamp/config/wagmi/custom-chains/ink.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/ink.png
Labels: chain

#3373 patch PR 1 of week ending 2/25/25
  packages/react-app-revamp/config/wagmi/custom-chains/ink.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/ink.png
  yarn.lock
Labels: patch

#3375 chore: reconfigure db schemas
  packages/react-app-revamp/database_schemas/supabase/analytics_contest_participants_v3 .sql
  packages/react-app-revamp/database_schemas/supabase/analytics_rewards_v3.sql
  packages/react-app-revamp/database_schemas/supabase/chain_params.sql
  packages/react-app-revamp/database_schemas/supabase/contest_participants_v3.sql
  packages/react-app-revamp/database_schemas/supabase/contests_v3.sql
  packages/react-app-revamp/database_schemas/supabase/email_signups.sql
  packages/react-app-revamp/database_schemas/supabase/extensions.sql
  packages/react-app-revamp/database_schemas/supabase/user_permissions.sql
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/bucket_file_format.json
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/bucket_rules.txt
  packages/react-app-revamp/supabase_schemas/merkle_tree_buckets/supabase_transfer_script.py
Labels: chore

#3380 chore: implement etherscan v2
  packages/react-app-revamp/components/TokenSearchModal/ERC20/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/NftList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/TokenList/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/components/UserTokens/index.tsx
  packages/react-app-revamp/components/TokenSearchModal/index.tsx
  packages/react-app-revamp/components/UI/DialogModalV4/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/config.ts
  packages/react-app-revamp/components/_pages/Create/components/RequirementsSettings/index.tsx
  packages/react-app-revamp/hooks/useFetchUserTokens/index.ts
  packages/react-app-revamp/lib/etherscan/index.ts
  packages/react-app-revamp/lib/permissioning/index.ts
Labels: chore

#3392 bugfix: fix contest duration calculation to show total days instead of remainder days
  packages/react-app-revamp/components/_pages/FeaturedContests/components/Contest.tsx
Labels: bugfix

#3393 chore: update sepolia public rpc
  packages/react-app-revamp/config/wagmi/custom-chains/sepolia.ts
Labels: chore

#3383 bugfix: add simulate contract to submit proposal fn
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
Labels: bugfix
