Repository jk-labs-inc/jokerace, pull requests merged in 2025-08, with the labels that each got.

#4271 enhancement: apply rootMargin to infinite scroll
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
Labels: enhancement

#4274 chore: replace react-type-animation lib with motion
  packages/react-app-revamp/components/UI/TypewriterCycler/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#4288 patch PR 8 of week ending 8/7/25
  packages/react-app-revamp/components/UI/TypewriterCycler/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/index.tsx
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4290 enhancement: use deploying wallet at the end for voting contests
  packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
  packages/react-app-revamp/components/_pages/Create/hooks/useSubmissionMerkle.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useContestsIndexV3/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/buckets/index.ts
  packages/react-app-revamp/hooks/useDeployContest/contracts/index.ts
  packages/react-app-revamp/hooks/useDeployContest/database/index.ts
  packages/react-app-revamp/hooks/useDeployContest/helpers/index.ts
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useDeployContest/types/index.ts
  packages/react-app-revamp/workers/indexContestParticipants.ts
Labels: enhancement

#4301 bugfix: fix proposal voters layout shift and refactor to use infiniteQuery
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
Labels: bugfix

#4302 chore: rm logging
  packages/react-app-revamp/components/_pages/Create/hooks/useSubmissionMerkle.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
Labels: chore

#4303 patch PR 1 of week ending 8/12/25
  packages/react-app-revamp/components/_pages/Create/hooks/useSubmissionMerkle.tsx
  packages/react-app-revamp/components/_pages/DialogModalProposal/index.tsx
  packages/react-app-revamp/components/_pages/ListProposalVotes/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useCastVotes/store.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeleteProposal/store.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4304 bugfix: fix vote button disabled state on mount
  packages/react-app-revamp/components/Voting/index.tsx
Labels: bugfix

#4305 bugfix: fix joketv label on contest deploy
  packages/react-app-revamp/components/_pages/Create/pages/ContestDeploying/index.tsx
Labels: bugfix

#4317 chore: use new clusters api
  packages/react-app-revamp/hooks/useProfileData/index.ts
Labels: chore

#4318 enhancement: use formatNumberAbbreviated on rewards
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/helpers/formatNumber.ts
Labels: enhancement

#4328 patch PR 3 of week ending 8/12/25
  packages/react-app-revamp/components/_pages/ListProposals/container.tsx
  packages/react-app-revamp/components/_pages/ListProposals/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Gallery/index.tsx
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/helpers/formatNumber.ts
  packages/react-app-revamp/hooks/useProfileData/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4329 enhancement: edit template text for price curves
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
Labels: enhancement

#4332 chore: update README env vars
  README.md
Labels: chore

#4338 merge sprint ending 8/12/25
  README.md
  packages/react-app-revamp/app/globals.css
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/ChargeInfo/components/Curve/Flat/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/ChargeInfo/index.tsx
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/MyVotes/index.tsx
  packages/react-app-revamp/components/Onramp/helpers/bridge.ts
  packages/react-app-revamp/components/Onramp/index.tsx
  packages/react-app-revamp/components/Onramp/providers/coinbase/index.tsx
  packages/react-app-revamp/components/Onramp/providers/coinbase/utils.ts
  packages/react-app-revamp/components/Voting/components/Mobile/index.tsx
  packages/react-app-revamp/components/Voting/components/VoteInfoSection/index.tsx
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Submissions/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/VotingPrice/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/FundPool/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/modules/shared/CreatorView/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/VotePrice/components/EndPrice/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Flat/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestRules/components/Description/utils.ts
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Desktop/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/components/InitialContent/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/components/ConfirmDialog/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalSendProposal/Mobile/index.tsx
  packages/react-app-revamp/components/_pages/DialogModalVoteForProposal/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/index.tsx
  packages/react-app-revamp/helpers/totalCharge.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/analytics.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/helpers.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useContest/store.tsx
  packages/react-app-revamp/hooks/useCreatorSplitDestination/index.ts
  packages/react-app-revamp/hooks/useCurrentPricePerVote/index.ts
  packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
  packages/react-app-revamp/hooks/useDeployContest/database/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/components/Error/index.tsx
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#4348 chore: fix ink rpc url
  packages/react-app-revamp/config/wagmi/custom-chains/ink.ts
Labels: chore

#4387 patch 8 of week ending 8/18/25
  Dockerfile
Labels: patch

#4391 chore: rm digital ocean docker push
  .github/workflows/nextjs_docker.yml
Labels: chore

#4393 chore: ensure resilience on errors
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/lib/rewards/contracts/batch-operations.ts
  packages/react-app-revamp/lib/rewards/contracts/core.ts
  packages/react-app-revamp/lib/rewards/contracts/fetching.ts
  packages/react-app-revamp/lib/rewards/contracts/validation.ts
Labels: chore

#4394 merge sprint end 8/19/25
  .github/workflows/nextjs_docker.yml
  packages/react-app-revamp/components/UI/GradientText/index.tsx
  packages/react-app-revamp/components/UI/UserProfileDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsCounter/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsSelfFundedMarquee/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useContest/index.ts
  packages/react-app-revamp/hooks/useGenerateProof/index.ts
  packages/react-app-revamp/hooks/useProposalVotes/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/lib/proposal/index.ts
  packages/react-app-revamp/lib/rewards/contracts/batch-operations.ts
  packages/react-app-revamp/lib/rewards/contracts/core.ts
  packages/react-app-revamp/lib/rewards/contracts/fetching.ts
  packages/react-app-revamp/lib/rewards/contracts/validation.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: sprint end

#4395 docs: rm DO docker README
  README.md
Labels: docs

#4402 chore: deprecate chains pt 2
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unichain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#4415 chore: turn off linting on build with new foundry update
  packages/forge/foundry.toml
Labels: chore

#4416 patch PR 1 of week ending 8/26/25
  README.md
  packages/forge/foundry.toml
  packages/react-app-revamp/config/wagmi/custom-chains/optimism.ts
  packages/react-app-revamp/config/wagmi/custom-chains/unichain.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4370 feat: implement price curve chart
  packages/react-app-revamp/components/ChargeLayout/components/Vote/components/ChargeInfo/components/Curve/Exponential/index.tsx
  packages/react-app-revamp/components/UI/MotionSpinner/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/VotingPrice/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/AnimatedDot/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/AxisBottom/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/AxisBottom/utils.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/AxisRight/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ChartBorders/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ChartError/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ChartGrid/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ChartLine/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ChartLoading/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/components/ReferenceLines/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/constants.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/helpers/index.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/hooks/useChartData.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/store.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/types.ts
  packages/react-app-revamp/components/_pages/Contest/components/PriceCurveChart/wrapper.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/VotePrice/components/EndPrice/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/VotePrice/components/LivePrice/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/Vote/components/Curves/components/ExponentialPricingOption/index.tsx
  packages/react-app-revamp/components/_pages/Submission/Mobile/components/Voting/index.tsx
  packages/react-app-revamp/helpers/dates.ts
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
  packages/react-app-revamp/helpers/formatBalance.ts
  packages/react-app-revamp/hooks/useCurrentPricePerVote/index.ts
  packages/react-app-revamp/hooks/useCurrentPricePerVoteWithRefetch/index.ts
  packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
  packages/react-app-revamp/hooks/usePriceCurveChartData/index.ts
  packages/react-app-revamp/hooks/usePriceCurvePoints/index.ts
  packages/react-app-revamp/lib/priceCurve/constants.ts
  packages/react-app-revamp/lib/priceCurve/index.ts
  packages/react-app-revamp/lib/priceCurve/types.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: feat

#4428 chore: deprecate chains pt3
  packages/react-app-revamp/config/wagmi/custom-chains/bnb.ts
  packages/react-app-revamp/config/wagmi/custom-chains/gnosis.ts
  packages/react-app-revamp/config/wagmi/custom-chains/scroll.ts
  packages/react-app-revamp/config/wagmi/custom-chains/sei.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
Labels: chore

#4440 chore: deprecate templates
  packages/react-app-revamp/components/CreateContestTypes/AnyoneCanPlay/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/Buttons/Next/index.tsx
  packages/react-app-revamp/components/_pages/Create/components/TemplateDropdown/index.tsx
  packages/react-app-revamp/components/_pages/Create/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestStart/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestUseTemplate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/art/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/art/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/debate/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/debate/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/demo-day/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/grants-round/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/hackathon/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/leaderboard/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/live-contest/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/live-contest/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/meme/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/meme/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/templates.ts
  packages/react-app-revamp/components/_pages/Create/templates/test-contest/config.ts
  packages/react-app-revamp/components/_pages/Create/templates/test-contest/index.tsx
  packages/react-app-revamp/components/_pages/Create/templates/types.ts
  packages/react-app-revamp/hooks/useSetContestTemplate/index.ts
Labels: chore
