Repository jk-labs-inc/jokerace, pull requests merged in 2025-07, with the labels that each got.

#4072 bugfix: fix compare versions for entrants delete functionality
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
Labels: bugfix

#4073 patch PR 2 of week ending 7/1/25
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
Labels: patch

#4098 patch 1 of week ending 7/8/25
  packages/react-app-revamp/config/wagmi/custom-chains/baseTestnet.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4110 chore: make charges to rewards pool default
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/store.tsx
Labels: chore

#4122 wording: update last 70
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/components/Split/index.tsx
Labels: wording

#4131 bugfix: fix percentage issue in vote price when below threshold
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/Timer/index.tsx
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
  packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
Labels: bugfix

#4132 patch PR 2 of week ending 7/15/25
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/Timer/index.tsx
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
  packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4140 chore: update no tiptap
  renovate.json
Labels: chore

#4143 chore: update story block explorer
  packages/react-app-revamp/config/wagmi/custom-chains/story.ts
Labels: chore

#4168 enhancement: show total rewards in contest page marquee
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsCounter/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
Labels: enhancement

#4170 wording: add chain name to onramp modal
  packages/react-app-revamp/components/Onramp/components/Buttons/FundFromAnotherChain/index.tsx
  packages/react-app-revamp/components/Onramp/index.tsx
Labels: wording

#4172 chain: add world, abstract, and hyperliquid chains
  packages/react-app-revamp/config/wagmi/custom-chains/abstract.ts
  packages/react-app-revamp/config/wagmi/custom-chains/hyperliquid.ts
  packages/react-app-revamp/config/wagmi/custom-chains/world.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/public/abstract.svg
  packages/react-app-revamp/public/hyperliquid.svg
  packages/react-app-revamp/public/world.png
Labels: chain

#4174 patch PR 1 of week ending 7/22/25
  packages/react-app-revamp/components/Onramp/components/Buttons/FundFromAnotherChain/index.tsx
  packages/react-app-revamp/components/Onramp/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsCounter/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsDisplay/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsMarquee/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/components/_pages/Contest/components/StickyCards/components/VotingQualifier/components/AnyoneCanVote/components/Exponential/components/Timer/index.tsx
  packages/react-app-revamp/config/wagmi/custom-chains/abstract.ts
  packages/react-app-revamp/config/wagmi/custom-chains/hyperliquid.ts
  packages/react-app-revamp/config/wagmi/custom-chains/story.ts
  packages/react-app-revamp/config/wagmi/custom-chains/world.ts
  packages/react-app-revamp/config/wagmi/index.ts
  packages/react-app-revamp/config/wagmi/server.ts
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useCurrentPricePercentageIncrease/index.ts
  packages/react-app-revamp/hooks/useFundRewards/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/layouts/LayoutViewContest/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/public/abstract.svg
  packages/react-app-revamp/public/hyperliquid.svg
  packages/react-app-revamp/public/world.png
  packages/react-app-revamp/tailwind.config.js
  renovate.json
  yarn.lock
Labels: patch

#4177 bugfix: fix marquee flash on contest page
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
Labels: bugfix

#4181 bugfix: fix rounding issues for end price
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
Labels: bugfix

#4182 patch PR 2 of week ending 7/22/25
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/index.tsx
  packages/react-app-revamp/helpers/exponentialMultiplier.ts
  packages/react-app-revamp/package.json
  yarn.lock
Labels: patch

#4186 enhancement: set exponential price curve as default in create flow
  packages/react-app-revamp/components/_pages/Create/hooks/useSetContestTypeConfig.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/AnyoneCanPlay/config.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/EntryBased/config.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Types/VotingBased/config.ts
  packages/react-app-revamp/components/_pages/Create/types.ts
  packages/react-app-revamp/hooks/useDeployContest/slices/contestMonetizationSlice.ts
Labels: enhancement

#4188 enhancement: add animation to vote and enter to earn marquee
  packages/react-app-revamp/components/_pages/Contest/components/RewardsInfo/components/RewardsMarquee/index.tsx
Labels: enhancement

#4197 chore: add const for percentage to creator
  packages/react-app-revamp/components/_pages/Contest/Rewards/components/Create/steps/ReviewPool/components/AddEarnings/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/components/Monetization/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestMonetization/components/Charge/components/SplitFeeDestination/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/components/Split/index.tsx
  packages/react-app-revamp/components/_pages/Landing/components/Explainer/index.tsx
  packages/react-app-revamp/constants/monetization.ts
  packages/react-app-revamp/hooks/useChargeDetails/index.ts
  packages/react-app-revamp/hooks/useDeployContest/slices/contestMonetizationSlice.ts
Labels: chore

#4208 patch PR 1 of week ending 7/29/25
  packages/react-app-revamp/components/Onramp/providers/coinbase/index.tsx
  packages/react-app-revamp/components/SendFunds/index.tsx
  packages/react-app-revamp/components/UI/Toast/components/Error/index.tsx
  packages/react-app-revamp/components/UI/Toast/index.tsx
  packages/react-app-revamp/components/UI/Toast/types.ts
  packages/react-app-revamp/components/Voting/index.tsx
  packages/react-app-revamp/components/_pages/Contest/Parameters/components/Earnings/components/Modal/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestConfirm/utils.ts
  packages/react-app-revamp/components/_pages/Create/pages/ContestTypes/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingRequirements/index.tsx
  packages/react-app-revamp/components/_pages/Create/pages/ContestVoting/components/VotingUploadCsv/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/components/ProposalLayout/Leaderboard/index.tsx
  packages/react-app-revamp/components/_pages/ProposalContent/index.tsx
  packages/react-app-revamp/hooks/useCancelRewards/index.ts
  packages/react-app-revamp/hooks/useCastVotes/index.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/analytics.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/email.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/helpers.ts
  packages/react-app-revamp/hooks/useCastVotes/utils/priceTracking.ts
  packages/react-app-revamp/hooks/useClaimRewards/index.ts
  packages/react-app-revamp/hooks/useComments/index.ts
  packages/react-app-revamp/hooks/useContestState/index.ts
  packages/react-app-revamp/hooks/useCreatorSplitDestination/index.ts
  packages/react-app-revamp/hooks/useDeleteProposal/index.tsx
  packages/react-app-revamp/hooks/useDeployContest/index.ts
  packages/react-app-revamp/hooks/useEditContestPrompt/index.ts
  packages/react-app-revamp/hooks/useEditContestTitle/index.ts
  packages/react-app-revamp/hooks/useEmailSignup/index.tsx
  packages/react-app-revamp/hooks/useError/index.ts
  packages/react-app-revamp/hooks/useSendToken/index.ts
  packages/react-app-revamp/hooks/useSubmitProposal/index.ts
  packages/react-app-revamp/hooks/useWithdrawRewards/index.tsx
  packages/react-app-revamp/lib/buckets/index.tsx
  packages/react-app-revamp/lib/image/imgur/index.tsx
  packages/react-app-revamp/package.json
  packages/react-app-revamp/utils/error.ts
  yarn.lock
Labels: patch

#4221 feat: add docker build and push
  .github/workflows/nextjs_docker.yml
  Dockerfile
  packages/react-app-revamp/next.config.js
Labels: feat

#4225 chore: switch avalanche to quicknode
  packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
Labels: chore

#4226 patch PR 4 of week ending 7/28/25
  packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
Labels: chore

#4228 patch PR 5 of week ending 7/28/25
  packages/react-app-revamp/config/wagmi/custom-chains/avalanche.ts
Labels: patch

#4237 chore: rm tailwind-logical
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#4238 chore: rm tailwind-line-clamp
  packages/react-app-revamp/package.json
  yarn.lock
Labels: chore

#4250 enhancement: add chain logo to onramp modal
  packages/react-app-revamp/components/Onramp/index.tsx
  packages/react-app-revamp/helpers/getChainLogo.ts
Labels: enhancement

#4251 patch PR 2 of week ending 8/5/25
  packages/react-app-revamp/components/Onramp/index.tsx
  packages/react-app-revamp/helpers/getChainLogo.ts
Labels: patch

#4266 patch PR 5 of week ending 8/5/25
  .github/workflows/nextjs_docker.yml
Labels: patch
